### ISSUE TITLE
background rendering doesn't render the whole (larger duration) animation

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1015]
**Synfig version & platform**:
1.3.11
Debian testing

**Issue description**:
I changed the duration of an animation to 59s. Background rendering stops at somewhere around 12s. Doesn't render further even if I place the time cursor manually on the gray areas.

![Screenshot_2019-11-22_19-43-22](https://user-images.githubusercontent.com/24214509/69432807-61f9be00-0d60-11ea-9ead-6dd4cff0d3ae.png)

**Comment by morevnaproject** [comment]
Please check memory usage on your system - background rendering stops when it getting close to memory limit.

**Comment by Keyikedalube** [comment]
If you mean RAM I have firefox and synfig running right now. The task manager indicates 1.4/3.8 GB is used. Looks there's still plenty enough room.

But if you mean video memory *(since I don't have a dedicated GPU equipped on my notebook computer)* then I think my computer is... only good enough for programming ;D

Maybe, I can work in small (10s) sections for my animation and clip them together afterward.
Overall I think this issue is hardware related and not synfig related. Should close this issue?

**Comment by morevnaproject** [comment]
@Keyikedalube Hmm... it uses RAM only, no GPU memory involved. So, there is some problem here/

@blackwarthog Any ideas?

**Comment by blackwarthog** [comment]
background renderer has an internal fixed hardcoded memory limit for background frames - 512Mb

in file synfig-studio/src/gui/workarearenderers/renderer_canvas.cpp at line 92

i thunk that eating of all avialable memory just for cache is not a good solution because an operating system has another applications to run at the same time with synfig. I think exists a solution to communicate with OS mark this memory as the cache for OS, and when system will require more memory we can free some from old preprendered images. But to implement it we need to do a three different solutions for Linux, for MacOS and for Windows - seems unreal.

we may add environment variable to control this limit, or add it to preferences

also we can set limit in depend from amount of installed RAM, but it will not work fine in some cases.
for example if you install more memory for specific task - not for extending a synfig cache - but to run a virtual machine for example, or for other user in multiuser machine, etc

in current synfig build, as a workaround, you may to reduce the size of visible workarea in pixels (do zoomout, or resize window to make visible worarea smaller) and press refresh button

**Comment by Keyikedalube** [comment]
> i thunk that eating of all avialable memory just for cache is not a good solution because an operating system has another applications to run at the same time with synfig.

Now I see the reason for not rendering larger duration animation (memory limit) is by design.

> as a workaround, you may to reduce the size of visible workarea in pixels

Or limit the animation length (in my case 10s max) and not suffer quality loss.

**Comment by blackwarthog** [comment]
> Or limit the animation length (in my case 10s max) and not suffer quality loss.

you doen no need to split the file
You cannot prerender the whole animation, but you have ability to select which part of your animation will be prerendered. Just set time cursor into middle of your animation and press 'refresh' button to free already prerendered data. After that prerenderer will render some frames forward and a little frames backward from the time cursor.

**Comment by Keyikedalube** [comment]
I'm closing this issue because I feel the current solution of hardcoding memory limit is better both for
- **User**: synfig just works out of the box and do not require user intervention to configure memory
- **Developer**: same code for all platforms, thus, easier to maintain
