### ISSUE TITLE
The colors change when I copy a group of layers to another file.

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#1022]
**Synfig version & platform**:
1.3.11. Debug build December 11, 2019. Archlinux 64.

**Issue description**:

When I copy and paste a layer or group of layers into another synfig file, whether it is empty or with other layers, the colors change and darken.

The color also changes when I import the file and export the canvas parameter.

I congratulate you, version 1.4 is going very well, keep it up. Thank you.

**sif file created by inkscape**:
[inksif.sif.zip](https://github.com/synfig/synfig/files/3907726/inksif.sif.zip)

**Copied to a blank sifz file**:
[copied.sifz.zip](https://github.com/synfig/synfig/files/3907728/copied.sifz.zip)

**Imported to a file with layers already created**:
[already.sifz.zip](https://github.com/synfig/synfig/files/3907733/already.sifz.zip)

**Copied to a file with layers already created**:
[already-2.sifz.zip](https://github.com/synfig/synfig/files/3907735/already-2.sifz.zip)

**Comment by morevnaproject** [comment]
This is result of recent change related with handling gamma in Synfig. In old versions Gamma for all documents was hardcoded value of 2.2. That resulted in non-uniform gradients and blending artifacts like described here - https://github.com/synfig/synfig/issues/933

Since commit a4bbdd72e57be5 the gamma is set to 1.0 by default. You can also set other values for specific files via "Canvas" -> "Properties".
![screenshot_001](https://user-images.githubusercontent.com/332868/71872004-a80eb380-314d-11ea-81d7-be318557a2eb.png)

In your particular case, I suggest to group copied layers and put a Color Correction Layer on top of the group. After that ser Gamma Adjustment parameter of  Color Correction Layer to 2.2:
![screenshot_002](https://user-images.githubusercontent.com/332868/71872187-44d15100-314e-11ea-9064-a034d44e05fa.png)

This will fix colors of copied layers.

**Comment by Gilraiser** [comment]
Ok, thank you very much
