### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by RezaSh13** [synfig/synfig#1030]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:
Hi, I have a manjaro :)
 plasma  ~  synfigstudio 
synfigstudio: error while loading shared libraries: libIlmImf-2_3.so.24: cannot open shared object file: No such file or directory

**Comment by RezaSh13** [comment]
aur/synfigstudio 1.2.2-1

**Comment by ice0** [comment]
Hi!
Can you check if you have openexr installed?

**Comment by RezaSh13** [comment]
openexr 2.4.0-4

**Comment by ice0** [comment]
Looks like Synfig Studio has been compiled with OpenEXR 2.3 and Manjaro has been updated to 2.4 now. 
Also i noticed what synfig-1.2.2 doesn't compile on latest Manjaro. Build is failed with an error:
```
error: conflicting declaration of C function ‘void icu_65::swap
```
same error with php53 (https://aur.archlinux.org/packages/php53/).

Some package seems to be broken.

AppImage from AUR works fine, just need to run it from
> /opt/appimages/synfigstudio.AppImage

because the startup script is also broken :(

**Comment by RezaSh13** [comment]
I used flatpack version :)

**Comment by ice0** [comment]
Nice. We are currently preparing the next stable release, so I plan to fix Manjaro after it is done.
