### ISSUE TITLE
Disable rendering in background by default

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1170]
We have negative feedback from our users, so i suggest to disable it by default until it will be polished and production ready.

@morevnaproject your opinion?

**Comment by Svarov-RZM** [comment]
I personally fully support this. The problem is, the more complex the artwork, the more lags the "Background rendering" introduces to the point where the animation couldn't even load. The reason for this is that rendering for each frame takes too much time and GUI thread 'swallows' any input so you can't even disable the background rendering.

Try loading and work with this animation in 1.3.12: https://forums.synfig.org/t/cinematographic-computer-interface-made-in-synfig/9465
I made it using Synfig 1.0.2/Windows 10/Intel Core i5 650. And on my computer I cannot even load it in said Synfig version. It just blocks in rendering after loading.

As an alternative solution, we can leave it enabled, but make an option in "Preferences" called something like "Disable background rendering" so user would have a more solid option to disable it for all projects.

**Comment by rodolforg** [comment]
The background rendering should be a bit smarter:
* don't struggle with GUI (maybe less threads?)
* don't render frame twice (one for workarea and other for thumbnail; maybe the thumbnail could be a simple downscale of the rendered workarea cache - it seems faster than process whole layer tree again)

But, indeed, it gives a bad impression how slow and laggy the interface suffers when user does a simple change.

**Comment by morevnaproject** [comment]
> As an alternative solution, we can leave it enabled, but make an option in "Preferences" called something like "Disable background rendering" so user would have a more solid option to disable it for all projects.

There is one more idea: we can make "Background rendering" button (the one at the top of workarea) behave globally - i.e. it can enable/disable background rendering for all opened (and created) documents. And make Synfig remember its status when application closed. So, user can choose to work with it or not.

> don't render frame twice (one for workarea and other for thumbnail; maybe the thumbnail could be a simple downscale of the rendered workarea cache - it seems faster than process whole layer tree again)

I've had impression this already works like that. Do we have all frames rendered twice? O__O

**Comment by morevnaproject** [comment]
Okay, I agree to make Background Rendering disabled by default.

**Comment by rodolforg** [comment]
> I've had impression this already works like that. Do we have all frames rendered twice? O__O

@morevnaproject That's what I suppose when I read this , for example:
https://github.com/synfig/synfig/blob/2df33799b30f777b6ff3818578ed376111094b49/synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp#L583-L597
