### ISSUE TITLE
Warp layer: Optimize in Draft mode

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1186]
Hi @blackwarthog!

I have tested Warp Layer and noticed it works differently when workarea in Preview mode:
it is faster in Preview and slower (but with higher quality) when mode is set to Final.
And that's great!

Still, when I switch to Draft mode the Warp Layer behaves the same way as in Preview mode.
Is it possible to do some optimizations to make it work even faster in Draft mode (by sacrificing the quality even more)?

If not, then it would be better to disable it in Draft mode.

Thanks!

**Comment by morevnaproject** [comment]
![screenshot_002](https://user-images.githubusercontent.com/332868/75606945-d5138d00-5b24-11ea-9be5-1b148f015512.png)

**Comment by blackwarthog** [comment]
> I have tested Warp Layer and noticed it works differently when workarea in Preview mode:
> it is faster in Preview and slower (but with higher quality) when mode is set to Final.
> And that's great!
> 
> Still, when I switch to Draft mode the Warp Layer behaves the same way as in Preview mode.
> Is it possible to do some optimizations to make it work even faster in Draft mode (by sacrificing the quality even more)?
> 
> If not, then it would be better to disable it in Draft mode.

i did nothing with it, it was work from the box
as i understand preview mode forces a nearest filter to all transformations

**Comment by morevnaproject** [comment]
> as i understand preview mode forces a nearest filter to all transformations

Yes.

So, what are the ways to optimize it more?

**Comment by blackwarthog** [comment]
> So, what are the ways to optimize it more?

hmmm... make test with trasformation of several vector regions and text

**Comment by blackwarthog** [comment]
CheckerBoard and Warp became more beautifull, so i've added two parameters to allow you to downgrade it to previous state:

Warp::interpolation
- here you can manually downgrade the quality of Warp transformation
by default quality is cubic (best), as like as in usual transformations for group

CheckerBoard::antialias
- by default is set to true, now you can disable it

Also i've added additional downgrading of underlayer for all non-affine transformations.
Underlayer paints with half resolution.


And other significant thing - this upgrade allow us to avoid parametric rendering by the proper way while using warp. In versions 1.3-1.4 we already worked without parametric rendering, but we had a lot of artifacts.
 - Previous version of warp layer was not worked properly.
 - Speed of previous of previous vesion was very depend by *count* of under layers - when you put several fast layers under the warp - these fast layers bocomes very slow - because parametric rendering was forsed to it.

* parametric rendering - is a rendering method not by full-raster at once, but by pixels. Calculation of each pixel goes trough all the layers by calling method get_pixel(coord) sequentially for all layers in context. It is very slow and result is always aliased. But it initially was a main idea of first synfig versions and we still have many layers that supports only this rendering method and it is ideal for gradients, distortions and fractals (but very bad for for regions). Problem with it - is when you falled into parametric rendering you cannot go back to the usual full-raster rendering. In other words each layer with parametric rendering forces us to use parametric rendeging for all under layers.

We cannot properly calculate reolution and size of background raster. For example - warp layer requires almost infinite size (but with low resolution) near the horizon and small size with very high resolution near the camera (by the 'size' i mean the size of raster in abstract synfig units, resolution is a count of actual pixels per unit). So we have a choise - to render under layers with parametric rendering or render under layer by full-raster with almost infinite size and very high resolution.

Or make the algorithm with using combination several under rasters with dfferent sizes and resolution (that we were done).

since version 1.2 or 1.3 (i does not remember) we partially solved this problem - we just made a heuristic algoritm that choses optimal size and resolution for backgroud raster, but it was not worked properly. In common case resolution was low.

**Comment by morevnaproject** [comment]
Thank you for fix and detailed explanations! ^__^
