### ISSUE TITLE
Uniform Synfig project source code indentation whitespace character

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1690]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
Synfig C++ source codes use tabs for indentation and some build scripts use spaces. This is annoying because I've configured my IDE to only insert tabs when tab key is pressed. That also means if I mistakenly use spacebars to indent... the IDE will autocorrect my mistakes.

Currently, I'm having trouble with existing synfig CMake scripts that are indented using space characters. To add new code I have to use another text editor to launch the script and edit my changes because QtCreator thinks I'm making a mistake unintentionally using spaces for indentation. So it keeps correcting my space characters to tabs.

I think all synfig text source files must use a uniform whitespace standard. Either tab or space but not a hybrid.

**Comment by Keyikedalube** [comment]
Once decision is made, a section about whitespace character on synfig's doc page would really help for many new contributors.

**Comment by BobSynfig** [comment]
Old debate, not only related to Synfig but in any development project

Personnaly, I hate use of tabs because... you need to configure their behaviour for each editor, for each user, for each source language...
Spaces remain consistent among editors/platforms.
I use 2 spaces per indentation level.

Some will argue that 1 tab = 1 indent level but it will be 2/3/4/8 spaces according the taste of the user, transformed as space or (like for you) retranscribed as tabs... Chaos!
Use of indentation level should be restrained to a minimum, it is linked to [Cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) and debugging will be easier with shorter/narrower functions.

And the fact we have wide screens nowadays doesn't mean we need to make long lines of code ;)

**Comment by Keyikedalube** [comment]
@BobSynfig I prefer spaces too. So no matter what platform or programming text editor, the indentation remains the same as intended by the author.

However, if a team love tabs over spaces then going all tabs is not a bad idea at all. Just that users have to be reminded to configure their editing program to follow the convention. Double work.

**Comment by ice0** [comment]
+1 for spaces. As for me there is no much difference between spaces and tabs, after you configure your IDE and it makes it automatically.

But if we talk about switching the whole project I think this will be a pain, because I am not sure about automatic formatting tools.

@rodolforg @morevnaproject your opinion?

**Comment by BobSynfig** [comment]
Please note that a global switching "now" would break the tracking of changes in source code of Git...
Thousands of lines would be considered as modified ^^
We would have to check file by file that proper indentation has been done properly (due to variable tab width)
And we would have to ensure that all the next contributions would respect this new convention in the future :/

For me, what count the most important is to do good vertical alignment of portions of code to improve readability, not the "condensed" automatic formatting of IDE.
Code should be readable like music sheet.
See for example this little commit https://github.com/synfig/synfig/commit/56dae1c789e4d184096fb5641c94bfbfb3c0502a#diff-27827726ffb01fc7a9083ccd08af55f6

**Comment by Keyikedalube** [comment]
How about changing files in 2 phases?
1. Modify all space indented CMake script files in one PR
2. Then Autotools in another PR

Leave C++ just as it is because there's no way one guy would happily reformat some 100+ files

Whereas build script files are more manageable :) At the most there'll be at most two (or more) script files in a single directory.

I could help with reformatting CMake files :)

**Comment by morevnaproject** [comment]
> @rodolforg @morevnaproject your opinion?

I am leaving the decision up to you guys! ^__^

**Comment by BobSynfig** [comment]
We could introduce a .editorconfig file in the project
Most of mainstream editors/IDE can use it natively or with a plugin :)
https://editorconfig.org/

**Comment by Keyikedalube** [comment]
EditorConfig looks like a great solution.

Sad that QtCreator still hasn't made it yet.
- https://github.com/editorconfig/editorconfig-qtcreator/issues/3
- https://bugreports.qt.io/browse/QTCREATORBUG-14013

**Comment by Keyikedalube** [comment]
However, I could use these two alternatives:
1. Code::Blocks
2. GNOME Builder

**Comment by Keyikedalube** [comment]
On QtCreator, anyone can hit **Ctrl+E Ctrl+V** to turn on and off whitespace visualization.

I personally find QtCreator a free and powerful open-source C++ IDE.

CLion and NetBeans seem OK but they need JVM and that doesn't play out well for users with limited resources (4GB RAM). JEdit and (some) remaining editors are just programming text editors that need user intervention setting up a project; specifying make commands, build commands, keyboard shortcuts, etc

I'm not having an easy time switching to another IDE...
However, if you guys decide to implement editorconfig file I can easily transition from qtcreator to GNOME Builder since the plugin is supported by default in it.

@ice0 Do you want me to make the whitespace changes in CMake scripts and make a PR or wait for other CMake PRs to be merged first. Because if I make the PR then existing CMake PR and mine might have conflicting changes.
- Bad outcome would be if existing PR gets merged first because that'll force me to rebase and undo my edits.
- Good outcome would be merging my changes first and let the existing PR rebase

**Comment by rodolforg** [comment]
> @rodolforg @morevnaproject your opinion?

I prefer tab indentations. Lol
I mean, I can set any indentation width this way (but I like the usual 4 blank spaces span).

I don't like 2-spaces indentation.
But it's all matter of taste anyway.

**Comment by Keyikedalube** [comment]
If I understood reading the example concept correctly reading [this](https://editorconfig.org/#example-file), I think enforcing EditorConfig space width might look like this:
```
[*.{h,cpp}]
indent_style = tab
indent_size = 4
```

But this issue https://github.com/editorconfig/editorconfig/issues/347 is worth looking at before you guys decide whether to enforce tab width or not.

**Comment by ice0** [comment]
Ok. Since we want to make the project consistent and not make global changes to it, it is better to leave tab indents. Also, I often use `git blame` to see the author of a commit, so a global change will break this functionality.
So here's my suggestion:
1) stay with tabs indents
2) fix indentation in CMake files when making changes to them.

**Comment by Keyikedalube** [comment]
Progressive changes sound better.

That means I can fix this PR #1577 CMake indentation myself, right?
And leave the rest untouched CMake script files alone...

The files I touched:
- synfig-studio/src/gui/CMakeLists.txt
- synfig-studio/ui/CMakeLists.txt

**Comment by morevnaproject** [comment]
> Also, I often use `git blame` to see the author of a commit, so a global change will break this functionality.

+1

**Comment by ice0** [comment]
>That means I can fix this PR #1577 CMake indentation myself, right?
Sure!

**Comment by Keyikedalube** [comment]
I think this issue is safe to close.

Maintainers only have to review the PR (involving build scripts) reminding contributors to make the changes for correct whitespace indentation character.

Or you could implement BobSynfig suggestion > EditorConfig < link and close this issue automatically :)

**Comment by Keyikedalube** [comment]
> I think all synfig text source files must use a uniform whitespace standard. Either tab or space but not a hybrid.

In some cases this is impossible. For instance, if you write a glade file by hand then obviously you'd indent it with tabs but if you use Glade program to design the GUI it's gonna be spaces automatically.

**Comment by ice0** [comment]
I think C ++ and CMake files will be enough.

**Comment by Keyikedalube** [comment]
@ice0 I should update my ShortcutsWindow glade file then. I wrote it with hand LOL. Glade program doesn't have an adaptor for that feature.

**Comment by ice0** [comment]
You can leave it as-is, especially if you are wrote it by hand.

**Comment by Keyikedalube** [comment]
Already pushed the updates :P
It's better with spaces for glade file indentation. Just keeping it consistent with three other glade files.

Maybe one day someone might implement `GtkShortcutsWindow` adaptor for Glade program and making changes to my handwritten file would turn out ugly with tabs and spaces all over.

**Comment by Keyikedalube** [comment]
I'm closing this issue because this is already being taken care of by maintainers reviewing PRs

There's no favorable software/feature solution so far... :(
EditorConfig was proposed but that plugin is still clone-and-build-it-yourself for QtCreator IDE for now
