### ISSUE TITLE
Don't render animation outside playback bounds

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1719]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
1. Set the playback bounds
2. Turn on Render feature

![Screenshot from 2020-09-30 16-56-05](https://user-images.githubusercontent.com/24214509/94680342-3dd31a00-033f-11eb-9e19-84da48792578.png)

Rendering all sides of the timeline is a bottleneck for long-duration animation. I'd love Synfig to be more efficient by rendering only those regions between left and right bound. That'll save up more resources and improve user's productivity too.

**Comment by FirasH** [comment]
Looked a bit into this feature... Great place to start with:
https://github.com/synfig/synfig/blob/7f1d91b10d20e877aa8ea7e4389b27a2f81e36b5/synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp#L515-L606

**Comment by FirasH** [comment]
I was able to get it rendering only inside the playback bounds and the single active frame outside the bounds.

Only one minor current drawback (or advantage?) is that background rendering works only when the playback is somewhere between the upper and lower bounds.
This is because the current logic used renders in the sequence either before or after current time and its contiguous frames.

**Comment by Keyikedalube** [comment]
Thanks, @FirasH 👍🏽

Pulling your changes and building now :)
