### ISSUE TITLE
[Synfig Studio] Opacity Parameter can be set arbitrarily outside of 0-1 bounds

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#2099]
**Synfig version & platform**:
master 41b7682

**Issue description**:
1) Create a new animation
2) Select the `Circle Tool` (works with other tools as well)
In the toolbox window you can set the Opacity value in the range [0,1]

3) Draw the Circle on canvas
4) Edit the `Opacity` Value in the `Parameters` window
The value can be set outside of the range [0,1]

The value should be bounded to the predefined range [0,1].

**Comment by Svarov-RZM** [comment]
It is an expected behavior. Sometimes you need to change opacity to higher/lower values in order to make the shape more noticeable in case of feathering or just to create a cool effect with blur/bevel layers. For example, create a circle, change 'Feather' to 1.0 and 'Opacity' to 10.0.

If you ask me, the parameter's name should have been kept as 'Amount'.

**Comment by FirasH** [comment]
Felt more like a useful bug to me, but I've never used it that way and could be useful in some cases for sure.

With this I mean that it's very counter intuitive the way it works even if it was called "Amount".
You add more of this "Amount" but is quite vague and in fact I've noticed by mistake that you could set any value.
Let's say you want `Opacity = -65` or `Opacity = 120` what does it mean for a generic user?

**Comment by Svarov-RZM** [comment]
> Let's say you want Opacity = -65 or Opacity = 120 what does it mean for a generic user?

Why would anyone want to set it to -65 or 120 out of the blue?
You, as a generic user, just experiment with it. The meaning is simple whether it's called 'Amount' or 'Opacity'. How much of a shape is present on screen. 1.0 - Solid (full opacity), 0 - Transparent, >1.0 - Will reduce feathering effect (because feathering is just transparency around corners), <0.0 - Will have similar effect but the colors will be inverted.

I personally don't see any problem with it. Besides, the user also able to set transparency in the color dialog of a shape which is a more user-friendly (obvious) way to do it.

**Comment by morevnaproject** [comment]
> It is an expected behavior.

Yes, this is expected behavior. Synfig uses HDRI colorspace, which allows to achieve interesting effects.

**Comment by FirasH** [comment]
@morevnaproject if that's the expected behavior of `Opacity` value I'm closing the issue 👍
