### ISSUE TITLE
Animating Active Layer Name of Switch Layer crashes Synfig Studio

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#2390]
**Describe the bug**
Animating `Active Layer Name` of the attached file crashes Synfig Studio.

**Step to Reproduce**
1. Open the attached animation file:
[SwitchCrash.zip](https://github.com/synfig/synfig/files/7436429/SwitchCrash.zip)

2. Turn on animate editing mode
3. In the `Layers` window select `Occhiale` > `Occhio SX`
4. In the `Parameters` window change `Active Layer Name`

Synfig Studio crashes consistently.

**Expected behavior**
Animation should be applied as usual.
The crash doesn't happen if animate mode is disabled.

**System information:**
 - OS: Windows
 - OS version: 10
 - Commit ID: 78e045f

**Additional comments**
The `Switch` was duplicated after exporting the `Active Layer Name`.

**Comment by rodolforg** [comment]
I tested on Linux here and looked at console output: master branch, AppImage 1.5.0/1.4.2/1.4.1, Debian 1.4.0, AppImage 1.2.1-testing-17.09.09 ... All of them output this when I follow the steps mention by FirasH.

```
(synfigstudio:481593): GLib-GObject-CRITICAL **: g_object_notify: assertion 'G_IS_OBJECT (object)' failed

(synfigstudio:481593): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

```

**Comment by ice0** [comment]
> I couldn't reproduce it here in the same commit ID ([78e045f](https://github.com/synfig/synfig/commit/78e045f940364f2754a09956c7990b5d270db833)).
> 
> Did you rebuild everything from scratch?

It reproduces for me on Linux when `G_DEBUG=fatal-criticals` is set.

**Comment by rodolforg** [comment]
I investigate it a bit - I did not advanced to a solution, but it also happens with Bone selection too (in bone parent selection) o.O

**Comment by morevnaproject** [comment]
Oh, this is critical.

**Comment by morevnaproject** [comment]
Does this happens with 1.4.2?

**Comment by ice0** [comment]
@morevnaproject That's strange, but 1.4.2 is not affected.

**Comment by rodolforg** [comment]
I "found" the problem: somewhere after an "activate" signal, a gtk closure tries to set the combobox active item with an invalid iter.
If we comment out this line:
https://github.com/synfig/synfig/blob/65303bc518cef3381bb537b0e29d61d1f3849e31/synfig-studio/src/gui/widgets/widget_value.cpp#L133
```c++
	sublayer_widget->signal_editing_done().connect(sigc::mem_fun(*this,&Widget_ValueBase::activate));
```
The problem is not thrown. However, user selects an item and have to click out combobox in order to this change has effect.

**Comment by ice0** [comment]
When I debugged this for the last time, I saw the following situation: 
- GTK emits a `MOUSE_RELEASE` event
- It goes down the hierarchy until it reaches `Gtk::ComboBox` (whose parent is `Widget_Sublayer`) 
- `Gtk::ComboBox` calls the `activate` signal and this is where the error occurs, because at that point the owner of the signal is already destroyed (`Widget_Sublayer`?) 

So, if I change this line of code, the error goes away, but this is not correct:
```
sublayer_widget=manage(new class Widget_Sublayer());
```
to
```
sublayer_widget=(new class Widget_Sublayer());
```
In this way sublayer_widget is not destroyed, so no error is thrown.

Why is this happening? I suppose that:
- `Widget_Value->Widget_Sublayer->Gtk::Combobox` is owned by `LayerParamTreeStore`
- When we switch a layer in the dropdown, it emits a signal that rebuilds the `LayerParamTreeStore`.
- At this moment this widgets is destroyed. 

This is the call stack, but I seem to be missing something here. .
```
sublayer_widget->signal_changed()
LayerTree::on_edited_value()-begin
Action::ValueNodeReplace::perform()
LayerParamTreeStore::on_value_node_replaced
LayerParamTreeStore::rebuild()
LayerParamTreeStore::rebuild()-end
LayerParamTreeStore::on_value_node_replaced-end
Action::ValueNodeReplace::perform()-end
LayerTree::on_edited_value()-end
~Widget_ValueBase
~ValueBase_Entry()
~Widget_Sublayer

(synfigstudio:15527): GLib-GObject-CRITICAL **: 12:11:29.703: g_object_notify: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by rodolforg** [comment]
OK.  I saw that `signal_value_node_replaced()` is called (almost) right after `signal_value_node_changed()` is called.
This somehow causes the crash.
The action `ValueNodeReplace` calls `ValueNode::replace()` that indirectly calls the signal `changed`. Then the first method changes the value node GUID and finally emits `signal_value_node_changed()`.
https://github.com/synfig/synfig/blob/1f702dfdcf9deb71eff5691e922dbb8803037b33/synfig-studio/src/synfigapp/actions/valuenodereplace.cpp#L169-L183

If we remove the `signal_value_node_replaced()` handler, the problem doesn't arise and Synfig does not crash.
However, I don't know if it is okay to do it, because ParameterTreeStore wouldn't get the GUID change (it doesn't seem to use it, though).
