### ISSUE TITLE
[Windows] Can't import file into a saved SIF animation (if both are on the same disk)

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#2410]
**Describe the bug**

> When I want to import a png to a sfz file, I get “you cannot import a file onto itself” IF I have already saved the sfz. I can only import them at the start.

(Reported by velizet on forums: https://forums.synfig.org/t/cannot-import-file-onto-itself/12721)

**To Reproduce**
1. Open Synfig
2. Save as a file
3. Menu File > Import
4. Select a PNG file
5. It doesn't accept the import with the error message "You cannot import a file to itself"

**Expected behavior**

**Screencast**
https://youtu.be/WRoxhZccthc
(By Bala)

**System information:**
 - OS: Windows
 - OS version: 11
 - Synfig version: 1.5.1

**Additional comments**
Bug introduced in #2239  and #2243 
Can't reproduce on Linux.

**Comment by ice0** [comment]
@rodolforg
This is a packaging problem. 
First I checked and the problem doesn't reproduced on latest master. 
Then I downloaded the archive from the latest build  https://ci.appveyor.com/api/buildjobs/60kig9u0ohdes0s5/artifacts/SynfigStudio-1.5.0-testing-2021-11-17-win64-27ea6.zip. Problem is not reproduced here too.

After that I replaced all third-party libs (GTK/GIO, etc) in the official release and the problem is gone.
It looks like a bug in `Glib/glibmm` which has already been fixed. 

@morevnaproject Can you take a look?
