### ISSUE TITLE
Portrait videos (9:16) videos are not rendering properly

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#2413]
When I render portrait video in synfig, the video comes out squeezed. Like this:

https://user-images.githubusercontent.com/50204208/141672708-e897ac69-8782-45af-a773-1db3b48667ff.mp4

**Expected behavior**
It should come out like this:

https://user-images.githubusercontent.com/50204208/141672588-9e827818-a937-44fb-b2b5-8a58c3de0ad0.mp4

**System information:**
 - OS: Windows 10 64bit 21h2

 - Commit ID: SynfigStudio-1.5.1-2021.10.21-win64-2cb6c

**Additional comments**
Stable version doesn't have this problem.

**Comment by rodolforg** [comment]
It works as expected on 1.5.0

**Comment by morevnaproject** [comment]
Just a blind shot: can this be because of changes in #2351? ^__^

**Comment by FirasH** [comment]
Issue is confirmed also on my side...
It's very likely that @morevnaproject intuition is correct

**Comment by FirasH** [comment]
As a temporary workaround, before exporting, untoggle the `Link width and height` and should export with the correct size.

**Comment by FirasH** [comment]
Here are the steps to consistently trigger this issue from scratch:

1) Create a new animation and add layer (e.g. a `Star`)
2) Go to: `Canvas > Properties`
3) Untoggle width/height (`Unlink width and height`)
4) Change default `Height` from 270 to 800 and keep `Width` value as 480
5) Click on `OK`
6) Go to: `File > Render` and press on `Render`

The output size is incorrect as if the total height of 800 is squeezed into 270 pixels.

If after step 5 width/height link is toggled off and then on, the issue is not reproduced. This toggling somehow reverts correctly the active flags.
