### ISSUE TITLE
Parameters and Timeline panels should show the same row selected.

### ISSUE THREAD

**Issue by ghost** [synfig/synfig#246]
When you select an item in one of the two panels, the same should be selected in the other panel.

![synfig_report_004](https://cloud.githubusercontent.com/assets/20951035/19144814/efeb6f7c-8bab-11e6-892a-70b0e7829c49.jpg)
##

**Comment by rodolforg** [comment]
Should it still be done @morevnaproject  ?

**Comment by morevnaproject** [comment]
@rodolforg I am afraid it is best to implement this after rewrite of TimeTrack Panel - https://github.com/synfig/synfig/issues/762

In particular, [many issues related with waypoints](https://github.com/synfig/synfig/labels/Waypoints) will require re-writing TimeTrack, as described [here](https://github.com/synfig/synfig/issues/762#issuecomment-480570931).

**Comment by rodolforg** [comment]
@morevnaproject interesting. I saw this too https://forums.synfig.org/t/waypoints-what-could-be-the-future-of/2944 (but it has some broken links).

Besides, there is this pinned issue https://github.com/synfig/synfig/issues/267 too – somewhat related, but simpler to solve – a while ago. I started to work on it but let it aside. I think I'll resume this work first, because TimeTrack depends on Params TreeView that depends on Layer TreeView and Dock......

**Comment by morevnaproject** [comment]
> (but it has some broken links).

Yes,  earlier I tried to fix all broken links, but probably missed a few ^__^"

> Besides, there is this pinned issue #267 too – somewhat related, but simpler to solve

Yes, this is also a good starting point! ^__^

> I think I'll resume this work first

Awesome! ^__^

**Comment by Keyikedalube** [comment]
Is this feature wanted/needed for the old timetrack?
