### ISSUE TITLE
Key animation tab/window rewrite

### ISSUE THREAD

**Issue by mray** [synfig/synfig#255]
Animating keyframes is very limited, things I miss are:

* "Graphs", "Time Tack", "Parameters" time track column should all be one merged tab
* selecting, editing, moving keys should be more versatile

This is probably on the development radar for quite some time.
I see this would be a major undertaking, what is the status on that?

**Comment by caryoscelus** [comment]
I don't see how merging parameters would help anything. It will only make interface less flexible and maybe just a bit more fancy. Somewhat tighter integration (e.g. #246) would be good, but not critical.

As for graphs - yeah, it might be a good idea to merge them. But it might turn out to be too complex for little benefit.

I think that better waypoint editing should have the most priority of what you mentioned, because it affects productivity the most.

Anyway, at some point when/if i finish multiple timelines i will be forced to dig some timetrack ui code. I'll see what can be done then.

**Comment by mray** [comment]
I didn't know about Keyframes vs. Waypoints. What are Keyframes used for?
If I understand both correctly I'm confused by the naming convention:

"Keyframes" build the *interpolated way* between defined values.
"Waypoints" describe the *key values* that get defined.

Anyway - I'm not sure what you have in mind with that new interpolation system, but it would be awesome to be able to control TCB parameters just like you can control splines. (maybe even render them the same way under the hood?)

**Comment by caryoscelus** [comment]
I think that was answered a ton of times, but anyway. In short, keyframes are used to automatically create waypoints when you create waypoints "near" (but not on) keyframe and to scale waypoint positions (if you have two kf and wp between them and move one of kf, wp will move accordingly to keep relative position between kfs). And i don't see how keyframes can be described as "build the way"..

As for interpolation - that's pretty much what i meant. It's just that i don't know how they work atm exactly and thus said "new system". Maybe it will only require editing current system.

And yeah, i hope it'll be possible to reuse rendering & editing code from regular curves to parameter-controlling curves.

**Comment by mray** [comment]
This is connected to #265 where I think the actual discussion needs to happen first.
