### ISSUE TITLE
Layer_CurveWarp with zoom at 1600% crashes Synfig

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#2594]
**Describe the bug**
Layer_CurveWarp with zoom at 1600% crashes Synfig

**To Reproduce**
1. Create a Rectangle in a new document
2. Add a CurveWarp layer above the rectangle layer
3. Disable/Inactivate this CurveWarp layer by clicking on the Layers Panel
4. Change workspace Zoom to 1600% (via `Ctrl`+`mouse scroll` or by typing the zoom level in the Zoom Dial widget)
5. Enable/Activate back that CurveWarp layer
6. Crash

**Expected behavior**
Synfig doesn't crash.

**System information:**
 - OS: Linux (Debian)
 - OS version: testing
 - Synfig version: >= 1.2.1, including master branch (1.0.2 works)

**Additional comments**
- Steps 3 and 5 can be both ignored, I just tried to see if the crash happens because I was zooming too fast or something like that.
- Step 1 can be any (composite) layer, actually. There must be one layer below the Curve Warp. Otherwise it doesn't crash. Filter or distortion layers don't seem to make it crash too.
- There is no crash for zoom levels lower than 1000% here.

**Comment by Kemosalamy** [comment]
the problem seems to be in this function specifically in synfig/synfig-studio/src/gui/workarea.cpp

![image](https://user-images.githubusercontent.com/81593733/160584594-dc8e65a7-fcb8-4290-a0a5-da77efaafb44.png)

**Comment by Kemosalamy** [comment]
After diving a bit more into this problem here is what I discovered:
the problem does lie indeed in refresh_dimension_info(kind of)
refresh_dimension_info is a function inside workarea.cpp as well.
the problem can be kind of isolated to the first 3 lines of the function: 

![image](https://user-images.githubusercontent.com/81593733/160872378-f80beaef-5f53-4a30-98f2-39e382feaf03.png)

Commenting the rest of the function has no effect on this crash(it is still reproducable with only these 3 lines). 
The problem is mainly with the values of w and h. specifically their product. After a lot of trial and error I discovered that for some reason when the product of w and h is somewhere greater than 12220554 that the application always crashes(12220554 was the last value I tested that worked and 12223068 was the first value that didn't work for me).

Somehow limiting the values to prevent the product of w and h from exceeding 12220554 prevents the crash however it limits the functionality of the zoom function.

I also suspect that this value(12220554) is dependent on the machine running the application. Locking the product of the w and h to 12220554 prevents the crash from happening. It is also specifically the product of theirs that is the problem as you can set w to 1 and y to 12220554 and the program wont crash still. Therefore I think the problem lies within some function using the values of w and h in some way and thereby causing a segmentation fault. The next chokepoint(basically where you can comment the code and stop seeing the crash from occuring) I found was this function in synfig/synfig-core/src/synfig/rendering/surface.cpp:

![image](https://user-images.githubusercontent.com/81593733/160873717-b9be6c48-1431-4671-896b-483afd3a48f6.png)

Once again limiting the product of this->width and this->height here prevents the crash, therefore meaning something is using these values again. 
The link between this function and the previous one is in:
synfig/synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp line 554

![image](https://user-images.githubusercontent.com/81593733/160874258-c9f8a550-d889-4f98-a442-3e301632db07.png)

**Comment by rodolforg** [comment]
I'm not sure the problem is renderer_canvas.cpp, as it happens also via synfig CLI, not only on Synfig Studio (GUI).

**Comment by hesham-essam** [comment]
I will take a stab at this issue if that's okay

**Comment by Kemosalamy** [comment]
@hesham-essam Here is what I discovered so far, hopefully it's of some use. My last progress with the issue after checking out the gdb segmentation fault backtrace seemed to be that the crash occurs due to 2 functions. specifically:

synfig/synfig-core/src/synfig/rendering/software/function/contour.cpp line 52 render_polyspan(

https://github.com/synfig/synfig/blob/473af1c1b1a3b990812825c7e01ea46ec3728fd9/synfig-core/src/synfig/rendering/software/function/contour.cpp#L52-L62

and 

synfig/synfig-core/src/synfig/context.cpp

https://github.com/synfig/synfig/blob/473af1c1b1a3b990812825c7e01ea46ec3728fd9/synfig-core/src/synfig/context.cpp#L260-L262

Each of these functions by themselves causes a segmentation fault when the steps described in the issue report above are performed. I'm still not exactly sure which line or why the crashes are occuring. Commenting out both of these functions(basically by putting a return at the beginning of the function) prevents the crash from occurring however it also breaks some of the rendering functionality.

**Comment by hesham-essam** [comment]
I tracked the cause of the problem, and it seems to be this bit of code
https://github.com/synfig/synfig/blob/e54c25dc051f6ad38f8ec2ed8ca95371be4a3cd4/synfig-core/src/modules/lyr_std/curvewarp.cpp#L443-L455
Specifically 
https://github.com/synfig/synfig/blob/e54c25dc051f6ad38f8ec2ed8ca95371be4a3cd4/synfig-core/src/modules/lyr_std/curvewarp.cpp#L449-L450
When zooming in, `set_wh` sets the width and height to a ridiculously large integers, that can't be allocated on memory (and in fact overflow to negative numbers when multiplied together to get the area).

SphereDistort does the same thing, and crashes just the same
https://github.com/synfig/synfig/blob/e54c25dc051f6ad38f8ec2ed8ca95371be4a3cd4/synfig-core/src/modules/lyr_std/sphere_distort.cpp#L339-L351

I believe this causes the rendering of these layers to be slow as well, since the target surface gets really big when zooming in.

I still don't fully understand what this function does exactly nor how layers operate in the rendering process, so I will investigate more.

**Comment by rodolforg** [comment]
Maybe the problem is the `pw` and `ph` values and these divisions:

https://github.com/synfig/synfig/blob/e54c25dc051f6ad38f8ec2ed8ca95371be4a3cd4/synfig-core/src/modules/lyr_std/curvewarp.cpp#L452-453

What if the calculation was computed other way? If `pw`/`ph` are too small, those calculations could be wrongly computed.

**Comment by hesham-essam** [comment]
I believe these hard coded values are a bug eitherway. They represent the area that should be rendered in canvas coordinates, and as we zoom in:
1. If we kept `pw` and `ph` constants, the area should get bigger in pixel coordinates (as is done right now).
2. If we kept the width and height constants, `pw` and `ph` would change so that the rendered image would not get any clearer as we zoom in.
