### ISSUE TITLE
issue with scale layer

### ISSUE THREAD

**Issue by ugajin-nijagu** [synfig/synfig#263]
See: [http://www.synfig.org/forums/viewtopic.php?f=15&t=10317&p=32542#p32532](http://www.synfig.org/forums/viewtopic.php?f=15&t=10317&p=32542#p32532)
Setting the scale layer amount to 1.0 seems to scale by more than 200% (double) and and closer to 300%
-u

http://wiki.synfig.org/Scale_Layer states:
The parameters of the Scale Layers are:
The parameters of the Scale Layers are:
Name Value Type
Amount 1.000000 real
Origin 0.000000u,0.000000u vector
For Amount, a positive value will scale up and a negative value will scale down. A value of 1.0 will double the original size of the object. A value of 0.5 will increase the object by 50%. While a value of -1.0 will reduce an object to half its original size.
The Origin is the center of the scale.
##

**Comment by caryoscelus** [comment]
Judging by git-blame, the exponential code (giving ~2.7 increase instead of 2) was used from the very beginning. I wonder why it's written otherwise in docs.

So, there are two possible solutions:

- leave code as is and fix docs to match it
- fix code to match docs, increase scale layer version and write transitional code

**Comment by morevnaproject** [comment]
Good point, @caryoscelus

**Comment by caryoscelus** [comment]
Now that i think about it, i don't even see any good reason to keep scale parameter exponential. It will be much more intuitive to just make it actual zoom amount and when you need exponential, you can use valuenode converters.

**Comment by morevnaproject** [comment]
Agree. Fixing documentation is just a faster solution. ^__^

**Comment by ugajin-nijagu** [comment]
The documentation isn't (IMHO) the problem.

**Comment by caryoscelus** [comment]
@ugajin-nijagu , even if what it says was never true?

**Comment by ugajin-nijagu** [comment]
Yes, even then @caryoscelus.

**Comment by mray** [comment]
I certainly would expect the scale layer to do work like this:

0.75 = 75%
1 = 100%
1.5 = 150%

I'm curious about the reason it isn't like that already...

**Comment by ugajin-nijagu** [comment]
It is probably worth adding a (temporary) note to the wiki, while any fix is considered. As I understand, to use the scale layer, a user needs to enter the inverse of the exponential function, or natural log as the amount. For example values of:

- 1.386294361 scales by a factor of 4.0
- 0.693147181 scales by a factor of 2.0
- 0.0 scales by a factor of 0.0
- -0.693147181 scales by a factor of 0.5
- -1.099612789001693 scales by a factor of 0.333
- -2.302585092994045 scale by a factor of 0.1

However, such a system may be far from ideal from a user's perspective. One simple fix might be to make Synfig return the inverse of the exponential function based on the value entered in the Amount parameter, and limiting the value type and range of posible values to positive doubles or something. Although not ideal from a content maker's perspective, it will make life a little easier.

The guide/manual will still need to be corrected as the line 'While a value of -1.0 will reduce an object to half its original size.' will remain incorrect.

**Comment by caryoscelus** [comment]
If i understand your proposal correctly, such fix might be harder to implement than proper fix, because it would mean adding special treatment to what currently is a generic real value.

As for proper fix, there's a question on how to approach compatibility: should values from an old file be modified to represent actual scale value directly or through adding exponent value node? Probably the latter, because in case scale value was linked, first solution will break it.

**Comment by ugajin-nijagu** [comment]
One option may be to let the thing silently fail, if a negative value is used. The guide will need to be updated in any event, and an advice may be included. Will the proposed quick fix cause backward compatibility issues?

**Comment by caryoscelus** [comment]
Negative value handling isn't the problem. The problem is using different values in UI and saves. Also it will cause a lot of confusion if value is linked somewhere.

**Comment by ugajin-nijagu** [comment]
Perhaps, I misunderstood your earlier comment. 

Re: the confusion that will be caused by linking - it is surely a matter of which value that you want to link. e.g. do you want to link to 0.693147181 or 2.0? 

What about having two linked parameter controls for the scale layer, Amount that takes the natural log and other that takes a scale factor, so that one can use either unit, and each updates the other? I am guessing that in this arrangement one might export either value. 

Sorry, if I am not much help. There is much I do not understand but, if I were designing a UI from scratch, I would like to be able to scale x and y independently. I can see how this might have to default in some cases to the same value with e.g. a circle layer primitive, but then one wonders why, there is only a circle and not an ellipse primitive, too.

**Comment by caryoscelus** [comment]
>it is surely a matter of which value that you want to link.

When talking about compatibility, it's a matter of which value you have already linked to.

>What about having two linked parameter controls for the scale layer, Amount that takes the natural log and other that takes a scale factor, so that one can use either unit, and each updates the other?

I'm not sure if it's as easy to implement as it sounds. And while it dodges compatibility problem, it introduces additional complexity (both from user and developer point of view). If someone is going to fix this issue, they might as well fix it properly so that we don't regret it later.

>Sorry, if I am not much help.

Noticing this and creating issue helps too. But beyond that it is mostly a matter of somebody actually fixing this stuff and requires somebody to be motivated to do it. You can edit wiki if you have access to it, though.

>I would like to be able to scale x and y independently

Me too. It's not an UI issue, though, but a feature that needs to be implemented.

**Comment by ugajin-nijagu** [comment]
Nope, can't edit, signed up, and can't login...

**Comment by caryoscelus** [comment]
I think wiki suffers a lot from spammers, so there's manual approval procedure. There are some plans to move docs into github as well, but i've no idea how soon that can happen.

**Comment by morevnaproject** [comment]
> I would like to be able to scale x and y independently

There is a Stretch Layer, that works exactly like this. It's in "Distortions" group.

> Nope, can't edit, signed up, and can't login...

You have put "Lorem ipsum" text in the "Bio" from field, so your request was considered as submitted by spambot. It's approved now.

**Comment by ugajin-nijagu** [comment]
How about renaming the Scale Layer as Zoom Layer, and relocating the Stretch Layer to the Transform menu and naming it Scale Layer?

**Comment by ugajin-nijagu** [comment]
Is this the correct forum to discuss possible changes to the wiki page?

**Comment by Darkspace65** [comment]
There is a documentation tab under development on the synfig forum : http://www.synfig.org/forums/ .

**Comment by ugajin-nijagu** [comment]
This issue can be closed.
See Wiki, and talk page.
