### ISSUE TITLE
Can't enable Dark Mode

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2637]
**Describe the bug**
On master branch, after PR #2632 dark mode is not possible to enable anymore.

**To Reproduce**
1. Start Synfig using this command: `SYNFIG_GTK_THEME=Adwaita /path/to/synfigstudio`
2. Choose "Edit" - "Preferences"
3. Enable "Dark UI theme" option
4. Click OK
6. Theme remains white

**Expected behavior**
UI should be switched to dark mode.

**System information:**
 - OS: Linux Mint
 - OS version: Linux Mint 19
 - Commit ID: 865f197

**Additional comments**
Note: On Linux user have to start Synfig with Adwaita theme - use `SYNFIG_GTK_THEME=Adwait`a environment variable for that. Without this variable Dark mode will not work. On Windows this env variable isn't necessary, as Adwaita is default theme shipped with Synfig.

In commit 865f197 the code, which reads SYNFIG_GTK_THEME variable is removed, and that's probably the reason why dark mode doesn't works -
https://github.com/synfig/synfig/commit/865f1977d0a3e4129a1031cc39d7ea7514bc7158#diff-f3ddd1c9f2f3b09a5e501ac594ba2178411d827018b634c530222e056d931ba1R2270-R2271

It also worth to look at this commit, which rewrites that part of code to GtkMM -
https://github.com/synfig/synfig/pull/1508/commits/0f52a144a99568e585c9f8eb8efa3cafb0a2dc02

**Comment by ice0** [comment]
@morevnaproject 
Need more details. I can't reproduce.

> In commit https://github.com/synfig/synfig/commit/865f1977d0a3e4129a1031cc39d7ea7514bc7158 the code, which reads SYNFIG_GTK_THEME variable is removed, and that's probably the reason why dark mode doesn't works

Yes. I removed it because the theme is already applied.

https://github.com/synfig/synfig/blob/2a11e920a6a8394184aaa3085d6150718657a451/synfig-studio/src/gui/dialogs/dialog_setup.cpp#L967-L968


The dark mode setting is still here:
https://github.com/synfig/synfig/blob/2a11e920a6a8394184aaa3085d6150718657a451/synfig-studio/src/gui/app.cpp#L2271-L2272

**Comment by ice0** [comment]
@morevnaproject 

Dark mode does not work in Mint 19 because Mint-Y did not support the `gtk-application-prefer-dark-theme` flag (https://github.com/linuxmint/mint-themes/issues/187)
For example:
```
# works
GTK_THEME=Adwaita:dark /path/to/synfigstudio

# doesn't work
GTK_THEME=Mint-Y:dark /path/to/synfigstudio

# Explicit dark theme selection (works)
GTK_THEME=Mint-Y-Dark /path/to/synfigstudio
```

Also, we can't use the `GTK_THEME` environment variable to set the theme, because it prevents dark mode from being changed.

I reverted my changes in this PR: #2645

**Comment by aalvarado** [comment]
If the snap version is used, the dark mode theme can be set in the desktop file here:

```
/var/lib/snapd/desktop/applications/synfigstudio_synfigstudio.desktop
```

replace the `Exec` line with:

```
Exec=env GTK_THEME=Adwaita:dark BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/synfigstudio_synfigstudio.desktop /snap/bin/synfigstudio %F
```

**Comment by ice0** [comment]
@aalvarado 
Thanks for the hint!
