### ISSUE TITLE
Windows: hang when opening a second .sif file from explorer

### ISSUE THREAD

**Issue by keithnbrown** [synfig/synfig#291]
**Synfig version & platform**: Windows 1.0.2

**Issue description**:

If an instance of synfig is running and you attempt to open a .sif file in an explorer window (not via the program itself), synfig hangs and needs to be terminated in task manager. This occurs regardless of if there's a file loaded into synfig or not.

Expected behavior would be that the opened sif file would appear in another instance or another tab

**Comment by keithnbrowncarlisle** [comment]
Has this been confirmed yet? Any plans to fix this? As it is incredibly annoying.

**Comment by morevnaproject** [comment]
Hello @keithnbrowncarlisle! Does this happens for you with the latest version (1.3.5)?

**Comment by keithnbrowncarlisle** [comment]
yes, still happening in 1.3.5

**Comment by keithnbrowncarlisle** [comment]
@morevnaproject 
also still happens in 1.3.6.

I get the feeling from looking at some of the issues that the windows development isn't as cared for or tested as much as other platforms, is this actually the case? As this isn't the only issue of stability the windows version has, even on "stable". If it wasn't for the amount of time it would take me to fill in bug reports, I would list them, but even a casual look at a windows build should turn up some crashes for anyone in your dev team.

Me and my boss are developers ourselves - we use synfig to produce the XML that our animation system reads. However, we don't have the spare time to contribute to development of the program ourselves to fix many of the fustrating issues we encounter during use. Otherwise we would have probably gennerated a few pull requests to fix these by now.

**Comment by ice0** [comment]
Hi, Keith! I'm currently working on bugs that lead to a Synfig crashing or being unstable. Also my primary system is Windows, so i can check and reproduce wrong Synfig behavior.  Your bug is confirmed and i will fix it soon.

**Comment by keithnbrowncarlisle** [comment]
awesome. I'll have a look and see what other crashes i can consistently reproduce and see if you've found them yet

**Comment by morevnaproject** [comment]
Does this still happens with 1.3.8?

**Comment by morevnaproject** [comment]
Should be fixed by c1b8488d24ef0737be63ed0e8a. 
Needs testing.

**Comment by morevnaproject** [comment]
Tested on Windows and Linux. Works perfectly!

Fix will be shipped in version 1.3.14.
