### ISSUE TITLE
AVG Reports the Software to be Malware

### ISSUE THREAD

**Issue by vivekchakraverty** [synfig/synfig#3021]
My AVG Anti-virus shows the software to be malware and almost refuses to let me install it even if i set file safety options off. Can you tell me whether the tile is safe to use?

**Comment by ice0** [comment]
Hi!

If you download installer from an official website (https://synfig.org) or from GitHub releases, then it is safe to use it. 
You can also check the installer on https://www.virustotal.com/ to make sure that most antivirus programs consider it safe. 
The problem is that since we are building the libraries ourselves, their hashes are different from those in the antivirus database.

**Comment by vivekchakraverty** [comment]
Thanks, thats reassuring!
