### ISSUE TITLE
Synfig: building stable 1.2.0 with opengl enabled fails

### ISSUE THREAD

**Issue by gerddie** [synfig/synfig#311]
**Synfig version & platform**:

version: 1.2.0 
Gentoo Linux amd64. 

**Issue description**:

Compilation fails at one point because:  

    no rule to create target  „rendering/opengl/internal/glsl/antialiased_textured_rect_fragment.glsl“

and in fact the directory is empty with the exception of *Makefile_insert* . 

If OpenGL is disabled, then it compiles fine.

**Comment by caryoscelus** [comment]
AFAIR i couldn't compile it either. Not sure if it is working at all, though - might be not worth trying to compile unless you are interested in developing.

**Comment by gerddie** [comment]
Well, I just created a Gentoo [ebuild](https://github.com/gerddie/gentoo-imaging/tree/master/media-gfx/synfigstudio) for the software, for that I have to compile it.

**Comment by caryoscelus** [comment]
Great to hear that! What i meant is *opengl renderer* might be not worth compiling, not synfig itself.

**Comment by onlyjob** [comment]
I've spent hours troubleshooting this problem and finally found that _.glsl_ files are missing in the [source tarball from Sourceforge](https://sourceforge.net/projects/synfig/files/releases/1.2.2/source/) but present [in this very GitHub repository](https://github.com/synfig/synfig/tree/v1.2.2/synfig-core/src/synfig/rendering/opengl/internal/glsl) as well as in the [source tarball Release](https://github.com/synfig/synfig/releases).

I could build Synfig-1.2.2 successfully with `--with-opengl` from the GitHub sources.

This issue is safe to close.

**Comment by morevnaproject** [comment]
@onlyjob Thanks for investigating! I think we need to modify scripts to include `.glsl` files into tarballs.

Ping @blackwarthog @ice0

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
