### ISSUE TITLE
Filters applied incorrectly

### ISSUE THREAD

**Issue by pwwoj** [synfig/synfig#316]
**1.2.0 on Win10**:
(we're more likely to help if you're using latest development builds)
This is major bug in current release!!!!

**Issue description**:
I add any of filter layers on top of my animation or as a filter on top of group and it zooms and filters/distorts whatever is in top left quarter of whole canvas. Tried that on 3 computers.
Installed version 1.0.2 and works fine. It is very bad!!!! 
Attached screenshots of unfiltered starr and then with filter on - on previous version works as expected - starr is in same place and have same size. 
Tried twirl and noise distort - similar incorrect behaviour.
![bug - no filter](https://cloud.githubusercontent.com/assets/17612942/22443918/0ec93d84-e741-11e6-96be-dcfded2339d4.png)
![bug - filter](https://cloud.githubusercontent.com/assets/17612942/22443919/0eca9c24-e741-11e6-96b5-14f09ce860f9.png)

**Comment by caryoscelus** [comment]
Perhaps related to https://github.com/synfig/synfig/issues/305. At least noise distort works fine for me on current master.

Note: if you don't mean to annoy people, it's better to refrain from unneeded extra punctuation and repeated complaints.

**Comment by pwwoj** [comment]
Sorry for punctuation but have animation project deadline on Wednesday and overreacted ... ;)

On 1/30/2017 11:32 PM, caryoscelus wrote:

Perhaps related to #305<https://github.com/synfig/synfig/issues/305>. At least noise distort works fine for me on current master.

Note: if you don't mean to annoy people, it's better to refrain from unneeded extra punctuation and repeated complaints.

**Comment by Darkspace65** [comment]
Hi! 
Yep. Seems to be lots of issues:
Using windows 10 and version 1.2.0
Curve Wrap shows some artifacts but they go away when you uncheck fast in the parameters panel.
Inside out blows up the entire image out of proportion. Bad. 
Noise distort throws the image off canvas. Bad.
Spherize seems to work fine.
Stretch looks ok.
Twirl throws the image off canvas. Bad
Wrap works fine and is the only effect that seems to gain speed from the new engine. All the others seem to slow down everything.
I assume blur is fixed in the new dev build.
I can understand his punctuations. It can't be like: if I want to do this you have to refer back to 1.0.2. If I do that you have to use the latest dev build but then that won't work... etc. Very bad if your are in the midst of a production or deadline, not to mention that you loose face when you want to show of a new version to a client and it does not work. Done that been there. Lol... 
Greetz!

**Comment by morevnaproject** [comment]
The latest development version fixes issue with Twirl and Noise Distort - https://morevnaproject.org/2017/02/04/synfig-studio-1-3-1-development/

Inside Out layer should be checked.

@Darkspace65 Please submit separate report about Curve Warp.
