### ISSUE TITLE
Circle tool and skeleton 

### ISSUE THREAD

**Issue by Darkspace65** [synfig/synfig#323]
Hi!
Synfig 1.3.1 & Windows 10:
If you draw a circle with the circle tool and attach a bone to it and rotate the bone, the circle gets distorted. 
If you draw a circle shape with the spline tool and attach a bone to it and rotate the bone, the circle shape does not distort. Bug or normal behaviour?
Greetz! 
![circle_skeleton](https://cloud.githubusercontent.com/assets/23108356/22750467/3671ca76-ee31-11e6-8ebc-27c58c77a9f4.png)

**Comment by FadhilKwan** [comment]
well, this is kinda awkward...

i just explored the circle's tangent a bit and found the reason....
**All the radius tangents in region layer from circle tool were split** (and merging them up fixed it),
**while the tangents from the spline tool already got their radius and angles merged from the start**

![circl wut](https://cloud.githubusercontent.com/assets/25135159/22754073/de411402-ee70-11e6-86bd-4d98f9a0cfb6.png)

to avoid such distortion, all tangents radius and angles have to be fully merged or splitted

for confirmation, try to do the link to bone again on splined circle **but** link it to bone after you split all the radius

**Comment by Darkspace65** [comment]
Hi!
Merging the tangent's radius partially fixed the distortion but the "fixed" circle does rotate correctly around the pivot point (the origin) of the bone and goes off center. 
Greetz!

**Comment by FadhilKwan** [comment]
ah, ok that's true....
how about trying that again, **but left this one unchecked**

![uncheckplsmate](https://cloud.githubusercontent.com/assets/25135159/22782303/ff678714-eef8-11e6-9445-ccb18c4b036f.png)

did that work....?

**Comment by Darkspace65** [comment]
Hi!
@FadhilKwan Yes! That worked. Thanks. 
Greetz!

**Comment by FadhilKwan** [comment]
Sure, no problem 😆  

i still didn't know how could those affect the whole circle-to-bone thing, it's pretty complex 😕 
But i glad it got its own workaround for now 😄

**Comment by caryoscelus** [comment]
Well, the thing is that bone-linking works with curve path, not outline/region layer. And curve path (accessible via "Vertices" parameter) is unaware of origin or any other transformation applied to layer. Moving origin (or having it moved by circle tool when you select that option) and then linking is similar in effect to trying to link when content layers are translated (e.g. via their group transformation) and skeleton is not. Coordinate system mismatch.

**Comment by FadhilKwan** [comment]
@caryoscelus  so... quoting back from @Darkspace65 , is that a bug or just a normal behavior...?   😕

**Comment by caryoscelus** [comment]
I wouldn't call that a bug. It certainly can be improved with the current destructive linking and take all (or at least some) transformations into account, but i'm not sure it's worth implementing, because i think that we need non-destructive skeleton linking (i.e. ability to adjust skeleton and add new vertices after linking) and if doing that straight, there will be no way to know about origin transformation.

In general, i think synfig has (too) many ways of moving stuff (vertices, origin, group layer, move layer) and it's not obvious what to use when. "Origin at center" option can be useful sometimes, but it's not something you can't live without. It might be better to eventually rid of origin for curve-based layers to avoid confusion.
