### ISSUE TITLE
No GUI localization

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#333]
**Synfig version & platform**:
1.3.1 / All platforms

**Issue description**:
Localization broken for Synfig-studio. Everything related to Synfig-core is fine. So GUI is only partially-translated.
![report](https://cloud.githubusercontent.com/assets/332868/23737452/c3291b18-04c5-11e7-8522-aff9e45a8b6b.png)

**Comment by southpawami** [comment]
This is so very true.  I have Japanese installed for when I use it, I very much find it in inefficient to have my programs in Japanese.  Synfig detects both languages installed and uses English and Japanese while running Synfig.  I thought this was an error in 1.2, so I installed 1.0, but this issue seems to have been there for a long time.

**Comment by blackwarthog** [comment]
I've fixed this bug: abdbf23

File "gui/localization.h" was not so redundant as expected

**Comment by morevnaproject** [comment]
The fix now shipped with latest development builds - https://morevnaproject.org/2017/04/23/synfig-studio-1-3-2-development/
