### ISSUE TITLE
Bug with linear subsampling type of the motion blur layer

### ISSUE THREAD

**Issue by Stas-Kholodilin** [synfig/synfig#3345]
When you set "subsample start amount" & "subsample end amount" to 0, and subsampling type to "linear", the object affected by this layer becomes black. If there are two objects in a group, they both turn into a black square.

1. Create any layer, for example, a star.
2. Add a motion blur layer.
3. Set the following parameters to the motion blur: aperture = 24 f, subsampling factor = 1.0, subsampling type = linear, Subsample Start Amount = 0.0, Subsample End Amount = 0.0.
4. The star disappears.
5. Group the star and motion blur layer.
6. Create a white background under this group.
7. You will see a black star.
8. If you add another shape layer in the group with the star and blur, both objects become one black rectangle.

The other subsampling types work well. In the screenshots, you can see three identical groups, but the only difference is the subsampling type of each motion blur layer.

![3](https://github.com/synfig/synfig/assets/29379779/0fa96414-6f2a-41f9-a165-003bae0e8993)
![2024-04-22_16-17](https://github.com/synfig/synfig/assets/29379779/38b7f658-1412-4d0b-8745-a69f02fd2412)
![2024-04-22_16-18](https://github.com/synfig/synfig/assets/29379779/01142253-16b9-4608-acbb-a90351a7b12b)
![2024-04-22_16-18_1](https://github.com/synfig/synfig/assets/29379779/c030b80d-6911-4a3f-8142-068879bbac87)

 - OS: Linux RED OS, 6.1.52-1, el7.3.x86_64 x86_64, MATE 1.26.0
 - Synfig version: 1.5.1

**Comment by rodolforg** [comment]
I read the code and made some additional tests:

- `Subsample Start Amount` and `Subsample End Amount` only matters to Linear `Subsampling type` (the code and the parameter tooltips says so)
- It is broken since 1.2.1 at least. Synfig version 1.0.2 works 'fine' - actually it renders nothing. I think it is strange though: it is just subsampling - should it really render nothing when they are zero?
