### ISSUE TITLE
AppImage won't start on fedora 40 (SynfigStudio-1.5.3-2024.08.23-linux64-3b7c5)

### ISSUE THREAD

**Issue by tolland** [synfig/synfig#3451]
**Describe the bug**
After downloading and chmod of the file, on first run it takes a while to create a font cache with a popup. On further runs, it pops a dialog which last for a fraction of a second, then crashes.

**To Reproduce**
1. Download file from <https://github.com/synfig/synfig/releases>
2. chmod +x to file
3. Execute appimage
5. See error:

```
[opt] $ ./SynfigStudio-1.5.3-2024.08.23-linux64-3b7c5.appimage
ls: /tmp/.mount_wkLHSu/usr/lib/libselinux.so.1: no version information available (required by ls)
find: /tmp/.mount_wkLHSu/usr/lib/libselinux.so.1: no version information available (required by find)
sed: /tmp/.mount_wkLHSu/usr/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_wkLHSu/usr/lib/libselinux.so.1: no version information available (required by sed)
/tmp/.mount_wkLHSu/usr/bin/synfigstudio: /tmp/.mount_wkLHSu/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libjack.so.0)
/tmp/.mount_wkLHSu/usr/bin/synfigstudio: /tmp/.mount_wkLHSu/usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /lib64/libjack.so.0)
/tmp/.mount_wkLHSu/usr/bin/synfigstudio: /tmp/.mount_wkLHSu/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib64/libjack.so.0)
/tmp/.mount_wkLHSu/usr/bin/synfigstudio: /tmp/.mount_wkLHSu/usr/lib/libselinux.so.1: no version information available (required by /lib64/libmount.so.1)
```

I tried
1. deleting font cache
2. extracting the app image. it also fails with similar message to above:
```
[opt] $ ./SynfigStudio-1.5.3-2024.08.23-linux64-3b7c5.appimage --appimage-extract
ls: /tmp/.mount_EfGIqw/usr/lib/libselinux.so.1: no version information available (required by ls)
find: /tmp/.mount_EfGIqw/usr/lib/libselinux.so.1: no version information available (required by find)
sed: /tmp/.mount_EfGIqw/usr/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_EfGIqw/usr/lib/libselinux.so.1: no version information available (required by sed)
/tmp/.mount_EfGIqw/usr/bin/synfigstudio: /tmp/.mount_EfGIqw/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib64/libjack.so.0)
/tmp/.mount_EfGIqw/usr/bin/synfigstudio: /tmp/.mount_EfGIqw/usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /lib64/libjack.so.0)
/tmp/.mount_EfGIqw/usr/bin/synfigstudio: /tmp/.mount_EfGIqw/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib64/libjack.so.0)
/tmp/.mount_EfGIqw/usr/bin/synfigstudio: /tmp/.mount_EfGIqw/usr/lib/libselinux.so.1: no version information available (required by /lib64/libmount.so.1)
```

same with appimage mount command.

**Expected behavior**
Application should start

**Screenshots**

**System information:**

- OS: Fedora Linux 40 (Workstation Edition) x86_64
- Kernel: 6.11.6-200.fc40.x86_64
- Uptime: 2 days, 16 hours, 45 mins
- Packages: 3285 (rpm), 1 (pkg), 40 (flatpak)
- Shell: bash 5.2.26
- Resolution: 1920x1080, 1920x1080, 2560x1080
- WM: i3
- Theme: Adwaita-dark [GTK2/3]
- Icons: Adwaita [GTK2/3]
- Terminal: konsole
- CPU: Intel i7-6700K (8) @ 4.200GHz
- GPU: NVIDIA GeForce GTX 1080
- Memory: 14183MiB / 48106MiB

**Additional comments**

other things attempted:

1. set selinux to permissive: no change
2.

**Comment by tolland** [comment]
flatpak version works from flathub. But might be worth mentioning this on the releases page if the appimage not works on fedora.

**Comment by BobSynfig** [comment]
Just saw your issue, randomly, as it has been opened and closed the same day ...
Test in VM, same error with F40 but ok now on F42
Why? Ask Fedora how they do their system, we had the same type of error on other systems, like any AppImage running at that time.
By the way, this was a well-know issue, depending sometimes on the fact that the AppImage was carrying old libs which where not compatible with the ones in the new systems, like for Enve, for example (with a patch of mine) https://github.com/MaurycyLiebner/enve/issues/304

> flatpak version works from flathub on f40 with i3wm.

Note that Flatpak carry gazillions libs and need to be installed on the system.
AppImages are meant to be runnable from a USB stick

> But might be worth mentioning this on the releases page if the appimage not works on fedora.

Depend on the version (F42 is ok, F40 wasn't).
Depend on what packages/versions are installed on your system.
We can't test neither all the available Linux distros, nor their flavors/spins (i3wm is not so common), nor the installed packages.
Why to declare incompatible with a specific distro when it is not even necessarily the app that is faulty?

> not sure why the extract and mount commands are not working though.

Synfig is still built with AppImage V1, these commands are only available since V2.
Can still be mounted on loopback to extract the content (see the documentation and/or the patch)

> so might have to just close and use the flatpak

If we have feedback, we can investigate.
But if you close the issue before anyone could look at it, there are only a few chances that we could become aware of it. ;)

Best regards :)
