### ISSUE TITLE
Problems with path, seek bar and PNG color when i open SIF file that created using Inkscape

### ISSUE THREAD

**Issue by raniaamina** [synfig/synfig#347]
Synfig 1.3.1 on Debian Based Linux

I try to open my *.sif file that i created using Inkscape. Unfortunately, some path doesn't appear well. 
![pemilihan_241](https://cloud.githubusercontent.com/assets/22146607/25301732/df8e5a38-2758-11e7-9f16-5d9206b045ed.png).
In other hand, when i open *.sif files, seek bar doesn't appear
![pemilihan_242](https://cloud.githubusercontent.com/assets/22146607/25301748/26d36212-2759-11e7-8129-2543ede5b9a4.png)

For alternative, i convert my Inkscape work to separated PNG files then combine them in Synfig. Some times, my color full PNG turn on white color, and i don't know the reason. 

What should i do?

**Comment by morevnaproject** [comment]
Hello @raniaamina 

> I try to open my *.sif file that i created using Inkscape. Unfortunately, some path doesn't appear well.

This is a problem of Inkscape's sif exporter. The best is contact maintainers of this extension. (Possibly, worths to submit to Inkscape's bugtacker, since exporter is officially included to Inkscape?)

> In other hand, when i open *.sif files, seek bar doesn't appear

This is because your file have zero-length timeline. Please choose "Canvas" -> "Properties" from menu, go to "Time" tab and set non-zero length of your animation. 

Food for thought to us: probably it's not the best decision to hide bottom bar when timeline length is zero?

> For alternative, i convert my Inkscape work to separated PNG files then combine them in Synfig. Some times, my color full PNG turn on white color, and i don't know the reason.

Please make sure you use RGB color mode during PNG export instead of  any other mode (grayscale, indexed). Can you please provide PNG file that imports incorrectly?

**Comment by raniaamina** [comment]
> This is a problem of Inkscape's sif exporter. The best is contact maintainers of this extension. (Possibly, worths to submit to Inkscape's bugtacker, since exporter is officially included to Inkscape?)

Ok, i understand. By the way, is there other best option to import svg file to synfig?

> This is because your file have zero-length timeline. Please choose "Canvas" -> "Properties" from menu, go to "Time" tab and set non-zero length of your animation.
> 
> Food for thought to us: probably it's not the best decision to hide bottom bar when timeline length is zero?

Thanks, this part solved!

Here, my PNG file that be white when imported to synfig
![latar](https://cloud.githubusercontent.com/assets/22146607/25519928/12d50336-2c24-11e7-9327-b7ec4f644278.png)

Thank very much for your respons :-)

**Comment by morevnaproject** [comment]
Submitted the file problem as separate issue - #366
