### ISSUE TITLE
Synfig is slow in windows 8 to 10

### ISSUE THREAD

**Issue by AlfredoArt** [synfig/synfig#358]
Synfig 1.2 - windows 8

When i work in windows 8 synfig is very low.
When i pic an action this react 2 seg to 7 seg later.

adobe suit is the best.

**Comment by morevnaproject** [comment]
Does this happens with any file?

**Comment by Keyikedalube** [comment]
Synfig stable release is now in v1.4

I think this issue is safe to be Closed.

**Comment by Keyikedalube** [comment]
> When i pic an action this react 2 seg to 7 seg later.

If you mean creating a rectangle/circle/polygon/etc layer on an empty canvas, I tried Synfig 1.2.2 on Windows 8, the action response is not slow but instant.

However, you'll start noticing performance degradation when there are more layers to render. Every synfig user faces this. There are ways to speed up your workflow (can also be applied to Synfig 1.4.0):
- Import and use raster images instead of letting Synfig tirelessly render complex layers like gradients and effects
- Turn off other layers while editing to speed up rendering your WIP layer
- Use low res or
- Zoom out your canvas for quick previewing

Since this issue is not targeted to a specific Synfig problem that can be addressed I'm closing this issue.
