### ISSUE TITLE
Undo does not work with sketch-tool (Synfig dev 1.3.3 Lubuntu 16.04.2)

### ISSUE THREAD

**Issue by WPFilmmaker** [synfig/synfig#392]
**Synfig version & platform**:
Synfig dev 1.3.3 on Lubuntu 16.04.2, 12GB ram, Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz [GeForce 940M] with latest nouveau drivers.

**Issue description**:
When you use other tools you can undo-redo but when I tried with sketch-tool I could not undo as the "edit->undo" menu voice is not active and if you try with keyboard it does not work.

**Comment by caryoscelus** [comment]
I'm pretty sure the reason for this is that sketch tool does not affect document and exists only for the duration of one session.

**Comment by WPFilmmaker** [comment]
so it is an intended behavior? if yes what if you do a mistake? you just erase it?

**Comment by caryoscelus** [comment]
No, i don't think it's intended. It's just that undo here is not as critical as it is with other features (and might require special treatment).

Personally i'm not sure sketch tool is worth using in this state at all.

**Comment by Keyikedalube** [comment]
I answered this same issue over here #458:

_Sketch tool has its own properties dock. There you would find undo button. Unfortunately, there's no redo action for this tool.
Since the sketch tool does not create its own layer, it makes sense to isolate its undo action from the rest._

Having two specific undo action is confusing users. This needs to be addressed in another new issue...
