### ISSUE TITLE
Please provide SynfigStudio AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [synfig/synfig#405]
Right now Morevna's SynfigStudio AppImage is uploaded to "somewhere" (where?) for each build. But for users this is a bit inconvenient.

Hence it would be nice if for releases and possibly also for continuous builds, the AppImage could be downloaded to the GitHub Releases page as well.

Personally I am using https://github.com/probonopd/uploadtool for this. Could easily be adapted to your needs.

Reference:
AppImage/AppImageHub#15

By the way:
How are the Morevna project and the Synfig project related? This is a bit confusing for users.

**Comment by morevnaproject** [comment]
> it would be nice if the AppImage could be downloaded to the GitHub Releases page as well.

This is good idea. Anyway, at the moment AppImages are available on SourceForge at  https://sourceforge.net/projects/synfig/files/releases/ and https://sourceforge.net/projects/synfig/files/snapshots/ 

> How are the Morevna project and the Synfig project related? This is a bit confusing for users.

Morevna Project is mentoring Synfig development since 2013. The team of Morevna Project is maintaining Synfig's builds/infrastructure and handling development of major features, as well as bugfixing. Also, Morevna Project is validating and testing Synfig in production (in the same way as Blender Institute does for Blender).

**Comment by probonopd** [comment]
Thanks for the clarification :+1: so I will consider builds from Morevna Project as "official upstream" for Synfig.

**Comment by morevnaproject** [comment]
@probonopd Now we providing appimages on GitHub Releases - https://github.com/synfig/synfig/releases/tag/v1.2.1

Thank you for the script, works like a charm!
