### ISSUE TITLE
Rename "Amount" to "Opacity"

### ISSUE THREAD

**Issue by alexandervrs** [synfig/synfig#411]
**Synfig version & platform**:
1.3.4 / Windows 10 64bit

**Issue description**:
"Amount" is a very arbitrary term for "Alpha", as such it should be renamed to "Alpha"

**Comment by morevnaproject** [comment]
Consider, that Alpha has inverse meaning to Amount.
I.e. when Amount = 1, then Alpha = 0.

**Comment by alexandervrs** [comment]
"Transparency" then perhaps or some other more recognizable term?

**Comment by caryoscelus** [comment]
>Consider, that Alpha has inverse meaning to Amount.
>I.e. when Amount = 1, then Alpha = 0.

That's not true. <https://en.wikipedia.org/wiki/RGBA_color_space>

**Comment by caryoscelus** [comment]
I suppose original reason for calling it "Amount" is uniformity: amount can be alpha, but can be also amount of effect (which may have nothing to do with transparency). However i agree that "alpha" would be more user-friendly name.

**Comment by alexandervrs** [comment]
I don't remember what setting the Amount to 0.0 did in Synfig, but I believe it made the object disappear. If that's the case, the term "Alpha" is correct.

**Comment by caryoscelus** [comment]
@alexandervrs yeah, that's pretty much what i'm saying.

**Comment by morevnaproject** [comment]
>>    Consider, that Alpha has inverse meaning to Amount.
>>    I.e. when Amount = 1, then Alpha = 0.

> That's not true. https://en.wikipedia.org/wiki/RGBA_color_space

Yes, I am wrong. Sorry.

> amount can be alpha, but can be also amount of effect (which may have nothing to do with transparency)

I remember at least one such case - Spherize Layer. Any other layers use Amount in terms other than transparency?

**Comment by caryoscelus** [comment]
>I remember at least one such case - Spherize Layer. Any other layers use Amount in terms other than transparency?

Stretch layer uses "Amount" for scaling factor, which is quite odd.

**Comment by morevnaproject** [comment]
Ok, then I suggest to go the following way:

1. Rename Amount parameter of Spherize and Stretch to something better  - i.e. "Size"?
2. Rename Amount for all other layers to "Alpha" or "Opacity".

**Comment by caryoscelus** [comment]
Hmm, there are also Scale & Rotate layers that use Amount.

- Spherize: tooltip suggest a nice name for it: Intensity (it's not really size - there's separate radius)
- Stretch: perhaps "Stretch factor"?
- Scale: "Scale factor" (though it still has user-friendliness issue: #263)
- Rotate: Angle

For the rest, Alpha or Opacity should be fine.

**Comment by morevnaproject** [comment]
"Rotate -> Angle" - agree.

For Spherize, Stretch and Scale I still feel "Size" as more appropriate.

**Comment by rodolforg** [comment]
What about `intensity` for every case?

**Comment by Jose-Moreno** [comment]
@rodolforg the problem I see is that `intensity` is also commonly associated with `Lightness` (when a color is bright), color saturation (when a color is intense or vibrant) or audio volume.

I guess `Amount` was originally meant to be used as a blanket term to be read along with the layer name (e.g Rotate amount, Scale amount, Noise distort amount, etc), but for the transparency related ones it doesn't make sense (e.g Circle Amount, Advanced Outline Amount, etc) 

If there's going to be a change in how these are read, I feel we can't be simplistic with this as there are already conventions that professional users expect from similar features in other applications.

That said for most layer effects I think using the same name or a general concept for each category might work "intuitively", although in some cases specific names might be better such as:

- **Blurs**: Motion Blur, Blur, Radial Blur -> Amount can be replaced by `Blur` or `Strength`
- **Distortions**: Amount -> `Distortion` for the whole category or specific terms for each such as:
    - Noise Distort -> `Strength`
    - Skeletal Deformation -> `Strength`
    - Spherize -> `Strength`
    - Stretch -> `Stretch` as it is self-explanatory.
    - Twirl - This is not related to amount but I find `Rotations` to be confusing -> `Direction` could be better because this only distorts CW or CCW from the radius center; there are no extra "rotations".
- **Transform**
    - Rotate Layer -> I also agree with `Angle ` could replace amount.
    - Scale layer -> Should be left as `Scale` as the term is pretty straightforward.
- Since the rest of the layers that use the "Amount" keyword are related to transparency, and as caryoscelus mentioned in the discussion years ago, in the context of RGBA color space most of the layers that use the "amount" for transparency should be better described as `Alpha`

**If there is still no consensus**, I'd at least have to ask to change the transparency related terms in all the layers for `Alpha` and leave the others as `Amount` as it's honestly not critical if we go by the object oriented property "reading" as I pointed out earlier.

Of course all of **these are merely suggestions**, but hopefully some terms are referenced from other professional apps so new users can use their existing knowledge to start using Synfig without too much hassle :v:

**Comment by rodolforg** [comment]
Got it :)

Something to remember: layers in layer list panel have a context menu with two related menu items: "Increase Amount" and "Decrease Amount".

**Comment by morevnaproject** [comment]
@Jose-Moreno I agree with most of your points. Just would like to suggest to use `Opacity` instead of `Alpha`. For my taste `Alpha` is more technical term, while `Opacity` is better understood even by non-professional audience. ^__^

**Comment by morevnaproject** [comment]
@ice0 I think this issue is ready for applying changes (Amount -> Opacity). ^__^

**Comment by morevnaproject** [comment]
"Amount" changed to "Opacity" for transparency-related parameters (via #1054). Please submit your suggestions for renaming other parameters as separate issues.
