### ISSUE TITLE
Won't get through verifying installation

### ISSUE THREAD

**Issue by yaakovshlomo** [synfig/synfig#431]
**Synfig version & platform**:
1.2.1 Stable

**Issue description**:
I have tried installing this on my Mac at least 8 times It only makes it through the verifjying about 5/8 of the way and then stalls out and quits. I have plenty of memory and disk space. I have completely uninstalled it and installed it again. I have cleared the way in system preferences to accept the download and install it. I really wanted Synfig, but just can't make it install. Can you please give me a hand.

Thank you, 
Yaakov

**Comment by morevnaproject** [comment]
Hello Yaakov! It is safe to skip verification when you open DMG file.

After DMG file opens, please copy SynfigStudio.app into your Application folder and start from there.

If you get "SynfigStudio can't be opened because it comes from a non identified developer" error, then you can solve this in the following way:

Please go to System Preferences > Security and privacy. Press the "Open anyway" button.

I hope that helps. ^__^
