### ISSUE TITLE
Circle layers have wrong selection area

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#442]
**Synfig version & platform**:
linux 1.3.4

**Issue description**:
A circle layer can be selected by clicking on its right at any distance. It makes circles of low Z depth so annoying you have to deactivate them.

**Comment by zeograd** [comment]
It seems like CurveArray::intersect(Real, Real, Point*) (in layer_shape.cpp:525)
starts with

		if((y < aabb.miny) || (y > aabb.maxy) || (x < aabb.minx)) return 0;
while it should rather be

		if((y < aabb.miny) || (y > aabb.maxy) || (x < aabb.minx) || (x > aabb.maxx)) return 0;

Note that doing so still allow to incorrectly select a circle in the 2 right areas between the actual curve and its AABB due to intersect_conic matching twice in the special degenerate accept case in layer_shape.cpp:241

		//degenerate accept - to the right and crossing the base line
		if(x > xmax)
		{
			return (y <= ymax && y >= ymin);
		}

The fact that the degenerate accept case of intersect_conic matches for x > xmax makes sense  that the calling intersect function did NOT checked x vs aabb.maxx but I don't understand the usefulness of the degenerate accept case for now (probably too broad as it is written now)

**Comment by zeograd** [comment]
It seems like CurveArray::intersect(Real, Real, Point*) (in layer_shape.cpp:525)
starts with

		if((y < aabb.miny) || (y > aabb.maxy) || (x < aabb.minx)) return 0;
while it should rather be

		if((y < aabb.miny) || (y > aabb.maxy) || (x < aabb.minx) || (x > aabb.maxx)) return 0;

Note that doing so still allow to incorrectly select a circle in the 2 right areas between the actual curve and its AABB due to intersect_conic matching twice in the special degenerate accept case in layer_shape.cpp:241

		//degenerate accept - to the right and crossing the base line
		if(x > xmax)
		{
			return (y <= ymax && y >= ymin);
		}

The fact that the degenerate accept case of intersect_conic matches for x > xmax makes sense  that the calling intersect function did NOT checked x vs aabb.maxx but I don't understand the usefulness of the degenerate accept case for now (probably too broad as it is written now)

**Comment by morevnaproject** [comment]
Thank you @zeograd! This is already better than before! I have committed your fix.

**Comment by zeograd** [comment]
You're welcome. I hoped I could do better but digging into a 12 years old function filled by conic maths without a good knowledge of the rest of synfig was a bit daunting.

**Comment by morevnaproject** [comment]
I found that this bug was introduced in c6f74576ecf and 2fbdbcfe6 when Circle Layer was rewritten to use Layer Shape. For some reason Layer Shape doesn't parse hit_check() function for this case correctly.

I have added explicit hit_check() function as a workaround. Closed via 38c383b0.

**Comment by morevnaproject** [comment]
Now shipped with Synfig 1.3.5 - https://morevnaproject.org/2017/12/25/synfig-studio-1-3-5/
