### ISSUE TITLE
Sketch tool does not render in side of a layer

### ISSUE THREAD

**Issue by Green468** [synfig/synfig#458]
**Synfig version & platform**:
Windows x64 platform version 1.2.1

**Issue description**:
The sketch tool render outside of every layer. Beside that, the undo/redo function seems not have any effect with Sketch tool.

**Comment by Keyikedalube** [comment]
> The sketch tool render outside of every layer

The [wiki](https://wiki.synfig.org/Sketch_Tool) says:

_The "Sketch Tool" allows you to draw freehand over the top of a Canvas._

Sketches are not meant to be rendered in the final product but act as drawing guides for editing. Hence, group layers and effects layers have no influence on this tool.

> the undo/redo function seems not have any effect with Sketch tool

Sketch tool has its own properties dock. There you would find undo button. Unfortunately, there's no redo action for this tool.
Since the sketch tool does not create its own layer, it makes sense to isolate its undo action from the rest.

https://user-images.githubusercontent.com/24214509/129513972-f63e87dc-a35a-45d1-986f-5652381e366b.mp4
