### ISSUE TITLE
Feature request : import sequence

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#461]
**Synfig version & platform**:
linux 1.3.4

**Issue description**:
At least, it would be nice to be able to import a sequence of "active layer name" for a switch layer, in the same way a sequence of .jpg image can be imported. This is essentially what importing a papagayo file does so I assume it shouldn't require a whole lot of work?

More generally, to make automated animation easier ( for example to represent scientific data ), it would be nice to either :
- have an "import sequence" option available when right-clicking on a parameter ; you could then select a file containing a sequence of frame+value records, which would be automatically set as waypoints.
- be able to convert a parameter to "sequence", which would take a filename as parameter

**Comment by Jose-Moreno** [comment]
@morevnaproject I think this is something that should be prioritized as well. To be honest the current "image sequence" import via .lst files is to put it kindly, not ideal. 

These would be the minimum requirements I can think of, if there are more please comment and i'll add them to this list:

- [ ] It should allow for flexible naming rules, either using regex or by having a naming convention template in the preferences.
    - [ ] It should import Named Image Sequences as Layer (via Switch Layer for drawing substitution in cut-out) e.g A_Mouth.png, B_Mouth.png, C_Mouth.png
    - [ ] It should import Numbered Image Sequences as Layer (via either Switch Layer or new layer type to support optimized playback of sequential individual images referenced from disk) e.g Mouth_001.png, Mouth_002.png, Mouth_003.png
    - [ ] It should import hybrid filenames that have both names and numbers. There could be a hard rule to force the user to always separate the numbering from the "name" with a separator if you intend to use numbers in your file name, prefix or suffix. e.g. my1stAnimation_0001.png
- [ ] It should be a separate option in the supported file list. e.g Image Sequence Files (*. etc)
- [ ] It should not need LST or any other type of intermediate files. Those would be reserved for papagayo support. e.g Papagayo List Files (*.lst)

**Example**:
Separator (optional) -> | (this is purely cosmetic, for presentation purposes, separators should actually be either: 
+ underscore ( _ )
+ plus ( + )
+ period ( . )
+ hyphen ( - )

**naming convention**: prefix | name | suffix | numbering | filetype
OR prefix_name_suffix_numbering.filetype

e.g PROJECTNAME_SC_SH01_00000.png
e.g myAnimation000001.svg
e.g myFirstAnimation.0001.jpg

I assume there is already capability to do this since the video / GIF import relies on the switch layer.

In the User Interface / User Experience front I see you guys like the import dialog to hide all the complexity such as selecting a specific file format, that's fine but it should be always clear that the user can select different files in different ways. To be honest I'd rather separate the audio, video, still image and image sequence, but as long as the "all supported files" menu becomes more descriptive and the documentation is improved, I think that should work.

Most importantly I think LST should only work for papagayo imports and the user should not be expected to hack their way around that for regular sequence imports. There simply needs to be an easier workflow for importing image sequences that come from other software such as Blender, Pencil2D, Krita or even other commercial applications like Harmony or Moho Pro.

As an anecdote, last time I tested this I had to research a LOT because it wasn't working at all. I looked up at the forum, looked up the old wiki, ended up having to configure VSCODE after trying different extensions, to automatically swap CLFR to LF endlines otherwise it would not let me import the images that I wanted. I had to do a python external script to iterate on the names to make the list since the tight formatting that LST files have is error prone if you do it manually. All of this should be done automatically without those intermediate files, trust me it's not practical.

Don't mean to sound harsh, but this is one of those basic functions that should work out of the box, and currently it's really hard for it to work as a professional or even a novice user expects. 

Hopefully this can happen for 1.4.0. I can't code in C++ but I'll gladly test any available solutions :smile:

**Comment by morevnaproject** [comment]
Hello @Jose-Moreno! Thank you for writing detailed summary on that! I am absolutely agree that current implementation of importing image sequences is horrible and needs improvement. ^__^

> I assume there is already capability to do this since the video / GIF import relies on the switch layer.

Actually, GIF/video import is not rely on switch layer, the things are organized a bit differently there. So, we should think how to extend current (image/video) import layer to accept filename patterns.

**Comment by morevnaproject** [comment]
@blackwarthog is working on this now - 3ca1e721189e8e3b21ac649462ed9e33adb9fea7

Waiting for solution for issue #978.

**Comment by morevnaproject** [comment]
Illustration of current implementation - https://www.youtube.com/watch?v=VYRbJ_Bp9YU

**Comment by morevnaproject** [comment]
The feature is shipped in Synfig 1.3.12.

How it works - https://www.youtube.com/watch?v=XoAvm4VmUG4

**Comment by morevnaproject** [comment]
The feature is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
