### ISSUE TITLE
Default render parameter are bad

### ISSUE THREAD

**Issue by Blaggejoe** [synfig/synfig#464]
Synfig version & platform:
Synfig Studio 1.2.1 / Win10 1709 64bit / Inkscape 0.92.2

Issue description:
The render-options are not really good with W10 and ffmpeg.

I used  the  parameters libx264-lossless with 2000 video rate. The .mp4 movie was shown by vlc but not with the build in video player from W10. It can also not played with omxplayer on raspberry pi. I must firts convert it with Handbrake as it is described here:
https://learn.adafruit.com/raspberry-pi-video-looper/omxplayer
But handbrake uses ffpmeg to convert the video in a useable format.
How can i convert it direct from synfig? Or are there some render-options missing?

Cheers Ralf

**Comment by morevnaproject** [comment]
The "libx264-lossless" codec is used by default because it is the best option to keep quality for further video editing (because it is... ahem.. lossless). ^__^

You can make the files playable on W10 by installing H264 coded. I recommend to try installing  FFDshow - https://sourceforge.net/projects/ffdshow-tryout/

Alternatively, if you do not care about quality loss, then you can use any other encoding settings. Choose "ffmpeg" target, then click "Parameters" button near the target dropdown. There you can select other codecs, like "Mpeg4", "huffyuv", "mjpeg".

![screenshot_009](https://user-images.githubusercontent.com/332868/33270787-cbc0af0e-d3b7-11e7-8f05-f8c3282f7085.png)

**Comment by Blaggejoe** [comment]
Hi Konstantin

Indeed, with the MPEG-4 part 2... settings -> no Problem on W10!
Thanks a lot!
So what would be nice is a progress bar for the Rendering. :)
Cheers Ralf

**Comment by morevnaproject** [comment]
> Indeed, with the MPEG-4 part 2... settings -> no Problem on W10!

We can make Mpeg4 as default rendering codec and set very high value for default bitrate (8000?). This way most users will get compatibility with their OS and we will avoid questions about video playback. 

If they will want lossless quality, then they will need to switch codec manually.

Would this change be good? Need to hear opinions. ^__^

> So what would be nice is a progress bar for the Rendering. :)

Yes, there is already request about that - #383.

**Comment by Blaggejoe** [comment]
For me MPEG4- part 2... with bitrate 2000 was ok.
Cheers

**Comment by wstaelens** [comment]
very confusing to select the correct codec to make an mp4 file which plays in Windows 10's default video player.
I just want to create an MP4 with best quality settings that works on the default video player of Windows 10. Not first spending 5 weeks on Wikipedia just to figure out that a specific mpeg-4 codec does not work by default on Windows 10.
 😞

**Comment by morevnaproject** [comment]
So, should we change default video rendering parameters to "MPEG4- part 2"?
We can also set default rendering format to "mp4" (video) instead of "png" (image sequence).

**Comment by morevnaproject** [comment]
Render defaults now to "avi" extension with "mpeg4" codec.

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
