### ISSUE TITLE
File Operations

### ISSUE THREAD

**Issue by iowaplayer** [synfig/synfig#489]
I'm running Synfig 1.2.1. on Windows 7

Whenever I try to open, save or import a file, i get an error pop up that says:
   There is no disk in the drive.  Please insert a disk into drive \Device\Harddisk5\DR5.

i have to click on cancel an average of 15 times before the error will go away and allow me to open, save or import a file.  

Also, there seems no way in Preferences to set default paths to open, save or import.

I'm new to Synfig and am really enjoying it.  It's very frustrating to have to go through this routine everytime i want to do something.

iowaplayer

**Comment by caryoscelus** [comment]
On Wed, 24 Jan 2018 13:52:45 -0800
iowaplayer <notifications@github.com> wrote:

> I'm running Synfig 1.2.1. on Windows 7
> 
> Whenever I try to open, save or import a file, i get an error pop up
> that says: There is no disk in the drive.  Please insert a disk into
> drive \Device\Harddisk5\DR5.
> 
> i have to click on cancel an average of 15 times before the error
> will go away and allow me to open, save or import a file.  
> 
> Also, there seems no way in Preferences to set default paths to open,
> save or import.
> 
> I'm new to Synfig and am really enjoying it.  It's very frustrating
> to have to go through this routine everytime i want to do something.
> 
> iowaplayer
> 

While i have no idea how it works on windows, there might be a way to
change default directory via launching options. For example, you can
try to launch synfig from command line (note that executable for ui is
called `synfigstudio`) from different places or afaik there's an
option to change working directory in launcher icon settings.

**Comment by iowaplayer** [comment]
from the error message, i get the impression that the open, save and import
operations are set up for linux and not windows. (the back slashes instead
of forward slashes).
i'm not so interested in changing the default directories as i am getting
rid of the damn error message and the need to cancel it so many times
before i can do my operation.

**Comment by caryoscelus** [comment]
On Wed, 24 Jan 2018 22:03:36 +0000 (UTC)
iowaplayer <notifications@github.com> wrote:

> from the error message, i get the impression that the open, save and
> import operations are set up for linux and not windows. (the back
> slashes instead of forward slashes).
> i'm not so interested in changing the default directories as i am
> getting rid of the damn error message and the need to cancel it so
> many times before i can do my operation.
> 

These things might be related. Btw, do i understand it right that the
popup shows up when you use path choosing dialogue and doesn't show up
when you simply save modified file?

Also you may try to look for similar errors in other gtk3 software.

**Comment by iowaplayer** [comment]
no, the error shows up every time i click file, then select open, save or import.   i'm not trying to do any path choosing.   once i get rid of the error by clicking cancel about 15 times, it will allow me to select directories until i get to the one i want.   

i'm not familiar with gtk3 software.  what is that?

**Comment by caryoscelus** [comment]
On Wed, 24 Jan 2018 14:16:23 -0800
iowaplayer <notifications@github.com> wrote:

> no, the error shows up every time i click file, then select open,
> save or import.   i'm not trying to do any path choosing.   once i
> get rid of the error by clicking cancel about 15 times, it will allow
> me to select directories until i get to the one i want.   

And what happens when you already saved document, then change it and
save again? I.e. when you don't need to choose path.


> i'm not familiar with gtk3 software.  what is that?

Gtk3 is framework used by some libre software (including synfig studio).
Though i don't know which have windows versions (the most famous gtk
software - gimp - is using gtk2). But you can try searching "windows
gtk3 There is no disk in the drive " or something like that. If it
doesn't get you anywhere or if you try other gtk3 software and it
doesn't show such error, then it's problem with synfig code or build.
But if you find something, you may either find a solution/workaround or
at least we'll know that the problem isn't with synfig.

**Comment by iowaplayer** [comment]
okay, i'll see what i can do.  thank you so much for your help! :)

**Comment by caryoscelus** [comment]
On Wed, 24 Jan 2018 14:28:15 -0800
iowaplayer <notifications@github.com> wrote:

> okay, i'll see what i can do.  thank you so much for your help! :)
> 
> 

np ;) i can check those myself later (when i get to browser). But i
won't be able to actually check whether solutions (if any) work anyway.

**Comment by caryoscelus** [comment]
Yeah, seems to be quite popular issue. https://github.com/Beep6581/RawTherapee/issues/3544 , https://answers.launchpad.net/inkscape/+question/129939 . Solutions vary from fixing "recently used files" list (see second link) to building on certain partition (you can try 1.3.5 build for now).

**Comment by iowaplayer** [comment]
i'm not real sure how the solutions you referenced apply to me as i don't have any usb drives.  i do have a c drive and an x drive, internal through my hard disk card.
the error occurs anytime i try to save, open or import, regardless of whether its for a new file or one i've modified.
i downloaded gimp 2.8.22 and it has no problems with saving, opening or exporting so it doesn't appear to be a gtk problem.  
sad to say, while i do know a tiny bit about software, i'm not at the level to be able to do the fixes the guys in those two references you sent me.
also, as far as i can tell, there's no way to select what version of synfig i download from the synfig.org website.  i can pick the current "stable version" or whatever their current development version is.

by the way, thanks for directing me to gtk.  i ended up downloading gimp and it is AWESOME!  i've been using microsoft visio and artrage 4 for my graphics and gimp opens up a whole new world! :)

**Comment by caryoscelus** [comment]
On Thu, 25 Jan 2018 11:33:13 -0800
iowaplayer <notifications@github.com> wrote:

> i'm not real sure how the solutions you referenced apply to me as i
> don't have any usb drives.  i do have a c drive and an x drive,
> internal through my hard disk card. the error occurs anytime i try to
> save, open or import, regardless of whether its for a new file or one
> i've modified. i downloaded gimp 2.8.22 and it has no problems with
> saving, opening or exporting so it doesn't appear to be a gtk
> problem. sad to say, while i do know a tiny bit about software, i'm
> not at the level to be able to do the fixes the guys in those two
> references you sent me. also, as far as i can tell, there's no way to
> select what version of synfig i download from the synfig.org
> website.  i can pick the current "stable version" or whatever their
> current development version is.

Since i'm not involved in morevna project builds (or even use them
for that matter), i can't meaningfully comment on that. But you seem to
be the first who reported the problem, so while it probably has
something to do with software, it might be possible to fix on your
side as well. I should note that gimp does not use gtk3 as far as i
know. You can try MyPaint, it's both interesting (especially if you
have a graphical tablet) and gtk3 based.

> by the way, thanks for directing me to gtk.  i ended up downloading
> gimp and it is AWESOME!  i've been using microsoft visio and artrage
> 4 for my graphics and gimp opens up a whole new world! :)
> 

Hmm, you might be also interested in Krita ;)

**Comment by caryoscelus** [comment]
Oh, and i also forgot to mention that you can download builds on https://github.com/synfig/synfig/releases, though i suppose you were already able to download something.

**Comment by morevnaproject** [comment]
Once I've had similar issue with our build of OpenToonz. So it seems that's not related with Gtk3 (OpenToonz is on QT).

@iowaplayer Please open a window showing your disc drives (usually called 'Computer") and post screenshot here.

**Comment by iowaplayer** [comment]
![image](https://user-images.githubusercontent.com/35783342/35427134-444abd0e-022d-11e8-961b-3acd996d0555.png)

here is the current configuration of my computer.

**Comment by morevnaproject** [comment]
Hello @iowaplayer! Apologies for delayed reply.

I have investigated the problem. It looks like this issue is pretty common for various applications, even for Adobe products:
- https://answers.microsoft.com/en-us/windows/forum/windows_7-hardware/there-is-no-disk-in-the-drive-please-insert-a-disk/da98f10d-019a-459c-8a86-7c71493fbdaf?msgId=92833a9b-e182-4e51-aca3-750975b43adb
- https://forums.adobe.com/thread/709495

So, this problem is related with some OS internals.

It worths to look at this particular answer -  https://forums.adobe.com/message/9451020#9451020

So, my questions:

1. Please let me know if you have any card reader device in your system?
2. Please try to insert any disc into your D: drive, start Synfig and try to save/open file. Does the problem appears again?

**Comment by morevnaproject** [comment]
Note to myself. This can be useful to solve the problem:
- https://superuser.com/questions/494475/can-a-single-volume-be-assigned-multiple-drive-letters
- https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by iowaplayer** [comment]
hi konstantin,

thanks for getting back to me. :)
i have no card reader device in my system, and my system is not configured
with a D: drive.

one thing i did notice though......while using open, save or import cause
the problem, open recent does not.  open recent works the way its supposed
to.  is there some difference between how open recent works and how open,
save or import works?

also, i gathered a bit more information about my system after reading the
web pages you directed me to:

i opened the device manager and discovered that under hard disks i had:
     Compact Flash USB Device               located on USB Mass Storage
     MS/MS-PRO USB Device                  located on H: Drive
     SD/MMC USB Device                        located on G: Drive

**Comment by iowaplayer** [comment]
hi Konstantin,

thanks for getting back to me! :)

i do not have any card reader device in my system.  never have had one.
and i don't have a D: drive on my system.

after reading the web pages you suggested, i opened control panel and got
into the device manager.  under hard disk i discovered the following:

Generic - Compact Flash USB Device                 location: USB Mass
Storage Device
Generic - MS/MS-Pro USB Device                       location: USB Mass
Storage Device
Generic - SD/MMC USB Device                           location: USB Mass
Storage Device
Generic - SM/xD Picture USB Device                   location: USB Mass
Storage Device
ST3240310CA                                                       location 3
ST500DM002-1BD142                                          location 0

the thing is, i don't use any mass storage except my two hard drives - the
two ST drives in the list above.

i did notice one thing that made me curious:

i get the error whenever i try to use open, save, or import.
i do NOT get the error when i try to use open recent.   open recent works
just fine!
is there a difference in how open recent works compared to how open, save
and import work?

thanks for all your help on this.  i appreciate it very much!

karen

**Comment by morevnaproject** [comment]
Hello @iowaplayer !

> i don't have a D: drive on my system

You do have one. I can see it on the image.
![screenshot_001](https://user-images.githubusercontent.com/332868/35605924-b937867e-067e-11e8-8922-ab6bfc4a3118.png)

Please try to insert any disc (CD or DVD) into your D: drive, start Synfig and try to save/open file. Does the problem appears again?

>  i opened the device manager and discovered that under hard disks i had:
> Compact Flash USB Device located on USB Mass Storage
> MS/MS-PRO USB Device located on H: Drive
> SD/MMC USB Device located on G: Drive

Thank you for this information! This actually indicates, that you DO have a card-reader device in your system. Please take a look carefully at the corpus of your PC. Do you see any slots to insert SD/MMC cards? It is possible the card-reader is mounted directly into corpus body.

> is there a difference in how open recent works compared to how open, save and import work?

Yes, opening through recent files menu doesn't involves listing files. That's why it doesn't asks for missing disc.

**Comment by Bill-Jobss** [comment]
Hi,

I have the same problem. So far I tried Synfig Studio 1.2.2, 1.3.10, and 1.3.11, and it happens every time I try to open or save a file. In version 1.3.11 the error message appears right after the program start. I have to click "Cancel" more than 20 times in order to close the message. I have a Windows 7 SP1 desktop with a card reader, DVD-drive and seven USB ports.

I never had such a problem with any other programs. Recent Files history is turned "off".

**Comment by BobSynfig** [comment]
Let's check this: https://github.com/Beep6581/RawTherapee/issues/3544#issuecomment-277814280

**Comment by Bill-Jobss** [comment]
I am glad that you guys are trying to maybe solve this bug. Let me know if you need any checking on my side. 

A few observations that I made:

I tried to start Synfig Studio 1.3.11 when a SD card was in the card reader, it did not help, the error message appeared right after the program start. Each time I clicked "Cancel", it reappeared with a different drive number (sometimes with the same number).

Then I tried to start Synfig Studio when a DVD disk was in the DVD drive. The message did not appear at all neither with the version 1.3.11, nor with the version 1.2.2.

I took the DVD disk out of the drive, and the message started to appear again, but this time it was a different message. It said: "There is no disk in the drive. Please insert a disk into drive F:", and it did not change after I clicked "Cancel", it was the exact same message every time. Now it takes "only" 5 to 7 clicks to completely get rid of the message (before it was over 20). "F" is my DVD-drive letter.

I prefer not to keep DVDs in the drive when I am not using them, so it still would be great if you could resolve the issue.

**Comment by morevnaproject** [comment]
> Then I tried to start Synfig Studio when a DVD disk was in the DVD drive. The message did not appear at all neither with the version 1.3.11, nor with the version 1.2.2.

Thank you for investigation - this note about DVD drive a very important information for us.

@BobSynfig Thank you, I think this could work!

**Comment by morevnaproject** [comment]
@BobSynfig I have applied the fix you found! ^__^

@Bill-Jobss Can you please test if this special build will give you "no disk in the drive" errors? - https://downloads.synfig.org/almost-1.3.11/SynfigStudio-1.3.10-testing-19.02.07-win64-47da2-seterrormode.zip

**Comment by BobSynfig** [comment]
In fact, it was initially found by @caryoscelus, I just "focused" on a specific comment ;)

**Comment by morevnaproject** [comment]
Ah, I has skipped the links in his comments because of the last sentence. ^__^

**Comment by Bill-Jobss** [comment]
Wow! You fixed it. No error messages neither after the program start, nor when opening or saving a project file. Thank you. Good job. So, approximately when do you expect the 1.3.11 will be ready?

**Comment by morevnaproject** [comment]
Thank you for testing!

I am building packages for 1.3.11 right now. Hopefully, will finish all release procedures this week. ^__^
Please consider, that it is going to be a **development** version - i.e. it still could have other issues and might not be ready for production use.
