### ISSUE TITLE
Wrong behavior with the menu in some keyboard shortcuts.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#546]
**Synfig version & platform**:
Manjaro Linux KDE (17.1.10)
Using:
Synfig 1.3.7
GTK+ 3.22.30
Built on May 9 2018
Built with:
ETL 1.3.7
Synfig API 01.02.00
Synfig library 50
GTK+ 3.22.30
GNU G++ 7.3.1

**Issue description**:

These tool hotkeys are not working correctly they give me access to the menú instead.

  Tool    -  Hotkeys  -  Menu problem.

Smooth move Tool -  Alt + v  -   Menu View
Circle Tool             -  Alt + c   -  Menu Canvas
Width Tool            -   Alt + w -   Menu Window
Fill Tool                -   Alt + f  -    Menu File
Eye Droper            -  Alt + e  -   Menu Edit

**Comment by ice0** [comment]
@ebarranco Enrique thank you for report, will be fixed ASAP.

**Comment by rockyhandsome1** [comment]
Hi @morevnaproject  I went through the code and would suggest
Shift forToolbox options and Alt for Menu options
This will avoid confusions for the users.
can I solve this bug?

**Comment by morevnaproject** [comment]
@rockyhandsome1 I'm afraid this issue is not an easy to solve.

If you will use Shift+Key for handling toolbox keybinding, then you will get affected by bugs #257 #292 and #303.

I.e. if you have Shift+C assigned to CircleTool, then Synfig will activate CircleTool everytime, when you press that combination - even if you just editing a layer name and typing "Clone" word (note capital "C" at the start).

See also my comment here - https://github.com/synfig/synfig/issues/629#issuecomment-471030956

**Comment by rodolforg** [comment]
@morevnaproject what about this here?

**Comment by morevnaproject** [comment]
@rodolforg I think it worth to try now!

> Shift for Toolbox options and Alt for Menu options

**Comment by Keyikedalube** [comment]
This issue is already solved in this PR #1823
