### ISSUE TITLE
Prerender to cache only when animation is played

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#611]
No need to waste CPU time when we are drawing

**Comment by morevnaproject** [comment]
I don't think that's a good idea. Sometimes user is not drawing, just moving his mouse around.
Let's formulate it like that: disable background rendering when user doing any modification on workarea. ^__^

**Comment by ice0** [comment]
AE workflow for example
https://youtu.be/ntz1bRb03Xc

**Comment by Jose-Moreno** [comment]
I agree with @ice0 on this one. I think it's a sensible way to approach the caching as normally you will only work on a handful of frames at a time, and even if you're using automatic interpolation, once you're ready to preview you can playback a first time so the program caches the frames that are played over, and then you can play a second time to get real-time fps.

One thing I should mention is that AE has also a "background" caching system to increase the speed of regular work, not specifically playback, because everytime you purge the cache and move your playback scrubber, if there's no data on the current frame it will take some time to load, particularly for Hi-res footage (2K+) with full sampling.

If there is doubt you could always provide a choice for the user to enable the "background" caching or the "on-frame" caching during playback.

**Comment by morevnaproject** [comment]
Still, I think rendering cache in background is useful (Krita does the same without a harm).

Having an option to disable background rendering is a good idea too. ^__^

**Comment by morevnaproject** [comment]
I think we will need one more option - to disable cache completely. This is needed to measure pure performance of rendering engine.

**Comment by ice0** [comment]
I was thinking about the option for the Synfig console tool (like --benchmark). So is it necessary for Synfig Studio?

**Comment by morevnaproject** [comment]
I think both needed. ^__^

**Comment by morevnaproject** [comment]
Implemented by @blackwarthog in 7f1d91b10d20e877aa8ea7e4389b27a2f81e36b5

**Comment by morevnaproject** [comment]
The fix is available for testing in Synfig Studio 1.3.11 - https://www.synfig.org/2019/02/16/synfig-studio-1-3-11-released/
