### ISSUE TITLE
Build instructions not work on Manjaro Linux

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#725]
Instruction at https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html#linux not work on Manjaro Linux.

See comments in https://www.patreon.com/posts/weekly-report-7-23934005

**Comment by BobSynfig** [comment]
Not even working with 1-setup-nix.sh? (This section has been removed it seems)

**Comment by ebarranco** [comment]
I used nix before but the documentation changed and the new script now says that I should install all the packages manually.

**Comment by morevnaproject** [comment]
Yes, we do not offer NIX as installation method anymore.

**Comment by rohitsanjay** [comment]
@morevnaproject 
I went through the comment in https://www.patreon.com/posts/weekly-report-7-23934005 ,
I found out that Manjaro Linux is Arch distribution different from Debian. And Arch uses pacman instead of apt-get to install dependencies.
this https://github.com/synfig/synfig/blob/master/1-setup-linux-native.sh don't have installation script for Manjaro Linux 
So, one of the solutions is to add scripts for Manjaro(Arch) Linux in https://github.com/synfig/synfig/blob/master/1-setup-linux-native.sh .
If I am going in the right direction allow me to work on this task.

**Comment by morevnaproject** [comment]
@rohitsanjay You are absolutely right! Your help is much appreciated here. ^__^

**Comment by morevnaproject** [comment]
Implemented in #770.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject is this still unresolved?

**Comment by ebarranco** [comment]
@rohitsanjay It's working for me since a while.

**Comment by BobSynfig** [comment]
I will try with a fresh virtual machine.
All the scripts need to be tested on a "virgin" system to ensure all required dependencies will be installed properly and not already existing in the system.

**Comment by morevnaproject** [comment]
@BobSynfig  Thanks for taking on this!

**Comment by BobSynfig** [comment]
Build successful following the official instructions found at https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html#linux on a fresh Manjaro KDE install.
Synfig is executing correctly.

The only thing I did after install was a `sudo pacman -Syu` to update the system.

During `./1-setup-linux-native.sh` phase, I just had a few minor, non-blocking errors:
![MinorErrors](https://user-images.githubusercontent.com/45494804/62120274-f3cd4f00-b2c9-11e9-84ac-7de4840bcd81.png)

All is working fine ;)

**Comment by morevnaproject** [comment]
@BobSynfig Thank you for testing! Closing now. ^__^
