### ISSUE TITLE
Display “static intervals” between waypoints

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#790]
If parameter value on a segment between two adjacent waypoints dosn't changes, then visualize that somehow.

Here's how that's done in Blender:
![screenshot_001](https://user-images.githubusercontent.com/332868/54899417-59679400-4f02-11e9-8203-abf3f8e6d2a4.png)

I suggest to display such intervals by connecting waypoints with a solid line:

![screenshot_002](https://user-images.githubusercontent.com/332868/54899679-312c6500-4f03-11e9-9e9b-e7ee232a5cd3.png)

**Comment by yshkp** [comment]
@morevnaproject This is a good feature for waypoints and I think I can replace my deliverable of single click state with this one. 
PS- Also check comments on suggestions.

**Comment by morevnaproject** [comment]
Yeah, I've just mentioned this in my review of your proposal draft. Sent it to you just now. ^__^

**Comment by yshkp** [comment]
@morevnaproject Surely I will do what you have asked me by that time.

**Comment by yshkp** [comment]
@morevnaproject As I have started working on the task that you gave me and on the early basis I came to an idea that: If it is allowed to select multiple rows which are rendered using cell renderer then automatically user can select multiple waypoints using CTRL key as the main issue was due to operating on a single row.
Please tell me if I am on the right track.

**Comment by morevnaproject** [comment]
@yshkp Since this is a question about issue #762, can you please post it there? That way our discussion will be on topic in right place. ^__^
