### ISSUE TITLE
synfig segfault building synfigstudio

### ISSUE THREAD

**Issue by limburgher** [synfig/synfig#822]
Synfig 1.2.2
Fedora 30+
make[2]: *** [Makefile:1416: 128x128/synfig_icon.png] Aborted (core dumped)
make[2]: Entering directory '/home/gwyn/fedora/git/synfigstudio/synfigstudio-1.2.2/images'
See: https://bugzilla.redhat.com/show_bug.cgi?id=1676105

**Comment by BobSynfig** [comment]
I updated my Fedora virtual machine to the newly released 30.
I will check asap.

**Comment by martrs** [comment]
There is a bug in synfig::FileSystem::fix_slashes(). The for-loop limit should be fixed.size() instead of filename.size().

**Comment by limburgher** [comment]
Thank worked, thank you so much!

**Comment by BobSynfig** [comment]
According the [Bug 1606466](https://bugzilla.redhat.com/show_bug.cgi?id=1606466), it was an issue to create images.
I faced it in the past.
Generally Synfig is already installed on the machine and the "synfig" (cli) command is already available.
We should have set a relative path to the generated binary (what I did on my machine in the past)
Here: `SYNFIG=synfig` in `/synfig-studio/images/Makefile.inc`
See also: https://github.com/synfig/synfig/issues/703

**Comment by morevnaproject** [comment]
> On Fedora, a root password has to be set: `sudo passwd root` in order to run autobuild/synfigstudio-linux-build.sh

Thanks for reporting! If I understand correctly, we can fix this by using `sudo` instead of `su` in build script.

> It seems there are also differences between tag 1.2.2 and stable branch (packages).

Hmm... you right, there is one commit different:

![screenshot_002](https://user-images.githubusercontent.com/332868/58371745-32e3ca80-7f3e-11e9-9b53-22d3e4f380f0.png)

@BobSynfig Can you please elaborate about circumstances which made you discover that? 

> We should have set a relative path to the generated binary (what I did on my machine in the past)

Or, better is to get done with #703, as you pointed out. ^__^

**Comment by morevnaproject** [comment]
> On Fedora, a root password has to be set: sudo passwd root in order to run autobuild/synfigstudio-linux-build.sh

Fixed in dd056a1b300cb0256a6df25238d5822ae00651de

**Comment by BobSynfig** [comment]
For root password in Fedora: https://wiki.synfig.org/index.php?title=Dev:Build_Instructions&diff=22074&oldid=21664

For the commits, they use stable branch, I compared with the tag 1.2.2

For the problem of compilation/images in 1.2.2 (and before), I "discovered" it when I was working from brand new installs of Fedora in Virtualbox.
Synfig needs to be installed first in order to build images.
If you already have installed Synfig on your system, no problem during the build as it is found in the path.
But if not already installed, as it is produced in a build directory instead of the system, it couldn't be found.
