### ISSUE TITLE
Will 2D's Flare runtime code benefit Synfig?

### ISSUE THREAD

**Issue by corbeeresearch** [synfig/synfig#823]
I just found another open source animation app:
https://www.2dimensions.com/about-flare

They offer their runtime codes here:
https://github.com/2d-inc
https://www.2dimensions.com/runtimes

Will their code be helpful to synfig?

**Comment by Jose-Moreno** [comment]
@corbeeresearch Unfortunately this is "free", not open-source. It reminds me of Spine, which is meant for modular animation. It does look impressive, but the runtimes (files that carry over to other apps the properties of the animated assets) are what's open-source, the software itself is not, and it's only "free" if you register an account, meaning you have to be online all the time to use it, plus they have a pricing scheme setup so you choose to pay for one if you want your files to be private. Obviously no one will want anyone to be able to see their work just because it's free.

Perhaps synfig could get to read or write those runtimes in order to export for their supported game engines and apps. But other than that the important features & capabilities are lost behind a closed source app. A shame really.

**Comment by corbeeresearch** [comment]
@Jose-Moreno Oh, that's sad... Oh well, a shame indeed.

**Comment by libreartist** [comment]
Hi, if, in this case, would openFX (api) be a relevant possibility in Synfig's roadmap?

**Comment by Jose-Moreno** [comment]
@libreartist That's something I hope it happens in the long run! :smile: although this issue was related to a game engine runtime exporter so Synfig could behave similar to DragonBones or Spine in that field.

There's still no official request for OpenFX integration, however currently you could theoretically use the python shell to integrate Natron's PyPlugs, but for OpenFX integration C++ binding is required.

Perhaps @corbeeresearch could rename this issue and make it a formal request to allow Synfig to export for C++, JS & other types of runtimes for game engines like [Godot](https://github.com/godotengine/godot), [GDevelop](https://github.com/4ian/GDevelop) and similar FOSS engines that support skeletal deformation, and soon, vector graphics.

**Comment by morevnaproject** [comment]
> would openFX (api) be a relevant possibility in Synfig's roadmap?

That's possible, I remember we have investigated possibility to integrate OpenFX with OpenToons  some time ago. This is best to discuss in separate issue. ^__^

> Perhaps @corbeeresearch could rename this issue and make it a formal request to allow Synfig to export for C++, JS & other types of runtimes for game engines like Godot, GDevelop and similar FOSS engines that support skeletal deformation, and soon, vector graphics.

I suggest to open separate discussion for that to keep discussion clear. ^__^

Also, it's best to open issue for support a specific thing, not everything in general (as it never will be closed). General discussion for supporting runtimes is more suitable for forums. ^__^

**Comment by Jose-Moreno** [comment]
@morevnaproject Well I meant that this thread should become the specific request to "add support for game engines runtime export" So just like Moho or Toonboom Harmony can export to Unity, I feel Synfig could get to a point where it can export to FOSS engines :thinking:
