### ISSUE TITLE
[Lottie exporter] Generate a simple HTML file together with JSON

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#833]
Currently, Lottie Exporter (#756) generates a plain JSON file, which is ready to insert into any Lottie player (HTML, Android, etc.).

I suggest to generate a simple HTML file to accompany JSON file, which will allow end user to easily playback animation in a web browser.

Sample HTML file code:
```
<!DOCTYPE html>
<html style="width: 100%;height: 100%">
<head>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.3/lottie.js"></script>
</head>
<body style="background-color:#ccc; margin: 0px;height: 100%; font-family: sans-serif;font-size: 10px">

<div style="width:100%;height:100%;background-color:#333;" id="bodymovin"></div>

<script>
    var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'file.sifz.1A15B56C.json'
    };
    var anim = bodymovin.loadAnimation(animData);
</script>
</body>
</html>
```

**Comment by AnishGG** [comment]
@morevnaproject, The commit https://github.com/synfig/synfig/pull/756/commits/2d6e70a8ca55adad4a06448efd2bad5ebad7af90 closes this issue.
Please have a look. ^_^

**Comment by ice0** [comment]
Hi, guys!
@AnishGG why not just use triple-quoted string for html? It will be more readable.

**Comment by AnishGG** [comment]
@ice0, Thank you for the suggestion. I will change it to triple-quoted string then!

**Comment by ice0** [comment]
@AnishGG looks good for me.

Few comments:
1. I think you don't need to escape single-quotes here (https://github.com/AnishGG/synfig/blob/d6b19424d2278e22f3a6f378ff7b0564431974da/synfig-studio/plugins/lottie-exporter/lottie-exporter.py#L72)
2. You can also use the format function to insert arguments inside. It will be better if you want to add more parameters to the code in the future.
An example of your code (Note: you need to escape braces `{{`):
```
html_text = """\
<!DOCTYPE html>
<html style="width: 100%;height: 100%">
<head>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.3/lottie.js"></script>
</head>
<body style="background-color:#ccc; margin: 0px;height: 100%; font-family: sans-serif;font-size: 10px">
<div style="width:100%;height:100%;background-color:#333;" id="bodymovin"></div>
<script>
    var animData = {{
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path:'{file_name}'
    }};
    var anim = bodymovin.loadAnimation(animData);
</script>
</body>
</html>"""

print(html_text.format(file_name=file_name))
```
3. Will be nice if you add some logger and logging information. Just to know what we can't parse layer or can't render it because it is inactive. (https://github.com/AnishGG/synfig/blob/d6b19424d2278e22f3a6f378ff7b0564431974da/synfig-studio/plugins/lottie-exporter/lottie-exporter.py#L29)

4. You have the same code here (https://github.com/AnishGG/synfig/blob/d6b19424d2278e22f3a6f378ff7b0564431974da/synfig-studio/plugins/lottie-exporter/lottie-exporter.py#L78) and here (https://github.com/AnishGG/synfig/blob/d6b19424d2278e22f3a6f378ff7b0564431974da/synfig-studio/plugins/lottie-exporter/lottie-exporter.py#L43) it will be good to move it inside function.
For example:
```
def write_to(filename, extension, data):
    new_name = filename.split(".")
    new_name = new_name[0] + "." + extension

    with open(new_name, "w") as f:
        f.write(data)


write_to("testfile.sif", "html", html_text)
```

5. Use two blank lines between functions (https://www.python.org/dev/peps/pep-0008/#blank-lines)

**Comment by AnishGG** [comment]
@ice0 I have taken care of points: 1, 2, 4 and 5. Will be implementing 3rd point soon!
Thanks

**Comment by morevnaproject** [comment]
@AnishGG Thank you, it is much easier to test animation export now!

Just a small suggestion: in HTML file it would be better to use relative path (i.e. filename only) instead of full path. That way the HTML + JSON file can be easily moved from one location to another (or transferred to other PC).

@ice0 I suggest to make point 3 as separate issue. ^__^

**Comment by AnishGG** [comment]
> in HTML file it would be better to use relative path

Fixed. :slightly_smiling_face:
