### ISSUE TITLE
use as api in c#

### ISSUE THREAD

**Issue by aghili371** [synfig/synfig#834]
i want to know it possible to use synfig like engine to develop animation dynamically by c#.net?

i want to create a video by c#.

**Comment by Jose-Moreno** [comment]
You'll probably have to first implement C++ bindings for C#, then research / use the API that interfaces with Synfig. 

I understand that there's already a way to interface with Synfig using Python for the so called "[plugins system](https://wiki.synfig.org/Doc:Plugins)", which allows you to create Python scripts that manipulate the SIFZ file (which is an xml / text file that organizes the multiple graphics and audio resources) this also works because the GUI is written with Python (GTK 3+) while the backend is realized with C++

So perhaps you could do it in the same way for C# but that is beyond the scope of this software so it'd have to be contributed by the community.

Here's the link to a C++ / C# set of tools & libraries for the binding part https://github.com/mono/CppSharp. 

But for the API you'd have to ask the developers if the Synfig API is properly exposed & documented, but It may be possible that you'd need to implement everything from scratch yourself using the bindings between C# and C++ and perhaps even Python... hopefully @morevnaproject can give us some more details about this, since it's actually an interesting topic, considering having C# support might make this project more appealing for future developers  due to the .NET / Mono ecosystem, and who knows, maybe even Microsoft would consider funding it as it did with Godot or other C# enabled open-source projects.

**Comment by morevnaproject** [comment]
We actually prefer to have Python bindings first. ^__^

> I understand that there's already a way to interface with Synfig using Python for the so called "plugins system"

What we have now for Python is actually a "quick hack" to allow quickly invoke Python scripts to parse contents of Synfig files.

In any case, I think this discussion is more suitable to take place on forums, rather than GitHub's issue tracker ^__^ - https://forums.synfig.org/
