### ISSUE TITLE
[Vectorization] Add progress bar 

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#854]
### This issue is a part of [Vectorization of bitmaps [GSoC 2019]](https://github.com/synfig/synfig/issues/735)

**Issue description**: Add a Progress bar so a user can see the partial progress feedback

Track the progress here -> https://github.com/synfig/synfig/milestone/5

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I have made the progress bar and function to control progress. 
As you mentioned I have to use `canvas_interface()->get_ui_interface()`. I saw examples in synfig where task and error are called using ui_interface. Do I also need to call some specific task?

PS: I tried adding the onemoment class but it shows nothing at all.

**Comment by morevnaproject** [comment]
Maybe try `amount_complete()`? - https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/render.cpp#L437 ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> Maybe try `amount_complete()`? - https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/render.cpp#L437 ^__^

it returns a bool I don't understand how `amount_complete(int, int)` will call `void
VectorizerSettings::set_progress(float value)`

**Comment by morevnaproject** [comment]
I suggest to take a look how ProgressCallback class is used during rendering process (in CLI and GUI).

**Comment by ankit-kumar-dwivedi** [comment]
> I suggest to take a look how ProgressCallback class is used during rendering process (in CLI and GUI).

@morevnaproject I saw but I am still not sure if we can interrupt an ongoing process using this method? Like if the user press cancel then vectorization should stop at current step(deleting all the intermediate data) without producing results and further.

What I saw and understand is we can do something like this.
```
// guess that this part will take 20% of time (from 0% to 20%)
SuperCallback scb(cb, 0, 20, 100); //cb is ProgressCallback
for(int i = 0; i < N; ++i) 
{ // ... // some code // ... 
if (!scb->amount_complete(i, N))
}
```
and according to @blackwarthog comment I need something like this to set_fraction() for progress bar

```
virtual bool amount_complete(int current, int total) 
{ 
dialog.progressbar->set_fraction((float)current/(float)total); 
App::process_all_events(); 
return !dialog.cancel_pressed; 
}
```
To be breifing on what all things the action need are as follow:
- a progresscallback class that can increase the progressbar by some amount. 
- This class will be passed to vCore so if in between cancel is pressed then reset progress and do not produce the result
- So the callback should be able to set progress and check cancel status by some method.

PS: The one_moment class is now working after full build and ready for use.

**Comment by morevnaproject** [comment]
> PS: The one_moment class is now working after full build and ready for use.

That's great news! Let me check that... ^__^

**Comment by morevnaproject** [comment]
I did a full rebuild (commit 07815e24ec) and "One Moment" window still doesn't work for me. ^__^"

**Comment by morevnaproject** [comment]
Here is an advice from @blackwarthog on that matter:

---

Do not mess up with "One moment" window. Go ahead and implement progressbar.

How to do that:

Check GlobalUIInterface class in `app.cpp`. This UI interface is passed to instance, when instance is created - 

https://github.com/synfig/synfig/blob/b2ca23c7eecba35485b98f76ce01ac0489545210/synfig-studio/src/gui/instance.cpp#L148

https://github.com/synfig/synfig/blob/b2ca23c7eecba35485b98f76ce01ac0489545210/synfig-studio/src/gui/app.cpp#L254

https://github.com/synfig/synfig/blob/b2ca23c7eecba35485b98f76ce01ac0489545210/synfig-studio/src/gui/app.cpp#L1489

So, just do the following:
1. Add progressbar somewhere into main Synfig window. 
2. Modify `amount_complete()` function, so it will set proper value to that progressbar.

---

I agree with that advice. In this case the progressbar will appear not inthe Vectorizersettings dialog, it will be a part of main Synfig window (and can be utilized for other routines in the future).

I suggest to put progressbar here -

![screenshot_001](https://user-images.githubusercontent.com/332868/63778770-a7e4e880-c90f-11e9-8512-cb8f64e93ef7.png)

Currently there we have a statusbar with text. I suggest to add progressbar in the same place, but hide it by default. The `amount_complete()` function will hide statusbar and show progressbar instead if progress value is >0% and < 100%. Otherwise it will do opposite - show statusbar and hide progressbar.

**Comment by ankit-kumar-dwivedi** [comment]
Working on this now!

**Comment by morevnaproject** [comment]
So, how the things are going?
I suggest to start with first step for now ^__^ -

> 1. Add progressbar somewhere into main Synfig window.

**Comment by morevnaproject** [comment]
Ah, my mistake! You have to use CanvasViewUIInterface class (in canvasview.cpp) instead of GlobalUIInterface class (in app.cpp). ^__^"

**Comment by morevnaproject** [comment]
...and you can call `instance->find_canvas_view(canvas)->get_ui_interface()` to get CanvasViewUIInterface inside of action.

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Ok, your last commit (https://github.com/ankit-kumar-dwivedi/synfig/commit/57c4fb9766da16abd9cc95496b2b412c67f9053f) is failing because the `instance` we get in action is belong to `synfigapp`. And it doesn't has `find_canvas_view()` method.
There is an `instance` class in `gui`, but since our code is located in action (`synfigapp`), we cannot reach it.

So, as advised by @blackwarthog, there is a simpler way:
just replace
```
get_canvas_interface()->get_instance()->find_canvas_view(get_canvas())->get_ui_interface()->amount_complete(1,5);
```
to 
```
get_canvas_interface()->get_ui_interface()->amount_complete(1,5);
```

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi I've looked at your latest code. To fix errors
just use `etl::handle<synfigapp::UIInterface>` instead of `etl::handle<UIInterface>` (in `centerlinevectorizer.cpp/centerlinevectorizer.h`)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi I have tested last commit from https://github.com/ankit-kumar-dwivedi/synfig/commits/master - ff03c78337d48528dd2bf5117e659ec0bab36aad
Progressbar is working, but UI is not updating, because application is freezes while doing vectorization. I suppose this happens because the vectorization process is happening in main thread.

@blackwarthog Am I right?

**Comment by morevnaproject** [comment]
I think we should look how it is done for Synfig's splash screen.
I.e. Synfig does something (loads settings) and displays a splash screen window with a progressbar. And that works.

So, maybe we should do something similar. I.e.:
When user clicks "Convert" button, we hide Vectorization Options WIndows, then display another window with progressbar (that window possibly should use separate thread?).

**Comment by morevnaproject** [comment]
@blackwarthog says that you need to add
```
studio::App::process_all_events();
```
after changing progress value.

See `splash.cpp` as example:
https://github.com/synfig/synfig/blob/1a6615962fe34cf2386c58290630d07fd99f3429/synfig-studio/src/gui/splash.cpp#L126-L135

**Comment by ankit-kumar-dwivedi** [comment]
Thanks @morevnaproject looks good now :)
