### ISSUE TITLE
AppImage version takes a long time to open

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#899]
**Synfig version & platform**:
1.3.11
1.2.2

on Fedora 30 workstation

**Issue description**:
I tried both AppImages and had the same trouble; they both took a long time (maybe around 2 mins) before Synfig program successfully launched its window.
Tried launching the program on Terminal and noticed the program hangs from this line:

Fontconfig error: Cannot load default config file

**Comment by BobSynfig** [comment]
Same on Fedora 30 with 1.3.11 (1.2.2 not tested), for the first execution.
Later it is faster, maybe doing some caching operation.

`Fontconfig error: Cannot load default config file` is known and due to differences of version of Fontconfig between Synfig (embedded lib) and Fedora (local font files).
But this doesn't prevent the app to work.
See https://github.com/synfig/synfig/issues/682 for full analysis.

For example, could be fixed using the old fontconfig files (https://bbs.archlinux.org/viewtopic.php?id=235643)
or using another Fontconfig lib in the app (https://src.fedoraproject.org/rpms/chromium/c/e00e15df7ee56234e38d6db3d6178b65aa22f937?branch=master)

**Comment by Keyikedalube** [comment]
I'm closing this issue.

Due to the reason that...
Synfig is also distributed as a flatpak app and in my opinion, this medium of packaging is better than using appimage because every user installing synfig using flatpak runs on the same runtime environment. So it's likely if a user encounters a problem on Ubuntu, same would be noticed by another user on Fedora, and so on for other distros too...

AppImage is great but font problems like this is unavoidable. One distro is stable and the other cutting edge. Choose one and the other breaks.

It'd be wise to stick and focus synfig packaging more on centralized medium such as flatpak and snaps.
