### ISSUE TITLE
[Lottie exporter] Add support for Advanced Outline Layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#935]
Make possible to export Advanced Outline Layer.

**Comment by JDFischbach** [comment]
Is there a workaround, to export advanced outline layers currently?

**Comment by AnishGG** [comment]
> Is there a workaround, to export advanced outline layers currently?

@JDFischbach Not yet

**Comment by AnishGG** [comment]
So I am trying to implement this feature. Before implementing, I need to understand how this layer is implemented in Synfig. 
I will be using this [Link](https://github.com/synfig/synfig/blob/15607089680af560ad031465d31878425af927eb/synfig-core/src/modules/mod_geometry/advanced_outline.cpp#L1043) for the implementation purposes [See [this](https://forums.synfig.org/t/gsoc-2019-export-animation-for-web/9507/117) conversation to know why I will be using an older version of advanced_outline].

As the advanced outline can have dashes, do we split the AdvOutline into multiple polygons and then render it? Can someone point me to the right direction here?

Ping @ice0 @rodolforg @morevnaproject

**Comment by rodolforg** [comment]
Maybe this helps you?
https://lottiefiles.com/3618-not-found

**Comment by AnishGG** [comment]
Thank you for pointing this out. We can create dashes in outline directly in lottie, but the outline will be restricted to a constant width. Same thing happened while implementing the export of `Outline` layer, and hence we had to use the basic shape_layer to export and implement the Synfig outlines.

**Comment by AnishGG** [comment]
> Maybe this helps you?
> https://lottiefiles.com/3618-not-found

Hence, we won't be able to use this.

**Comment by AnishGG** [comment]
If we have an advanced outline with multiple dashes(say 4 dashes visible to us), then we will need to render 4 polygons, right? But [here](https://github.com/synfig/synfig/blob/15607089680af560ad031465d31878425af927eb/synfig-core/src/modules/mod_geometry/advanced_outline.cpp#L1040-L1052) in advanced outline, we are always rendering at maximum of 3 polygons.
Can someone clarify/correct me on this.

**Comment by rodolforg** [comment]
AFAIK, current implementation of AdvancedOutline first computes the shape as it was a straight line (but with variable width and possibly dashed). Then it 'bends' this 'line' finally shaping the contour (and this is incredibly crazy *.* I really congratulate who did it!)

**Comment by AnishGG** [comment]
So, I tried to use the advanced outline from the same `.sif` file both in the master branch and [this](https://github.com/synfig/synfig/tree/15607089680af560ad031465d31878425af927eb) branch(which I will be using as the reference to export the advanced outline), but both have a slightly different result which can be seen below:
`Master branch results`:
![new_synfig](https://user-images.githubusercontent.com/30872212/122343608-82512500-cf63-11eb-8fe0-b602d8e59782.png)

`Previous branch results`:
![old_synfig](https://user-images.githubusercontent.com/30872212/122343679-96952200-cf63-11eb-856a-befc75fa3b1a.png)

`File used`:
[check_advanced_outline.zip](https://github.com/synfig/synfig/files/6667886/check_advanced_outline.zip)

`Question`:
Even if I am able to export the advanced outline, is it desirable to get this result(as shown in the 2nd picture), because it is slightly different from the master version.

Ping: @rodolforg @ice0 :D

**Comment by AnishGG** [comment]
Making note of some doubts:
https://github.com/synfig/synfig/blob/15607089680af560ad031465d31878425af927eb/synfig-core/src/modules/mod_geometry/advanced_outline.cpp#L640
Should this be: `scwiter = --scwplist.end();`

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
